// Code generated by ent, DO NOT EDIT.

package gate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the gate type in the database.
	Label = "gate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLiveURL holds the string denoting the live_url field in the database.
	FieldLiveURL = "live_url"
	// FieldShadowURL holds the string denoting the shadow_url field in the database.
	FieldShadowURL = "shadow_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldDiffIgnoredFields holds the string denoting the diff_ignored_fields field in the database.
	FieldDiffIgnoredFields = "diff_ignored_fields"
	// FieldDiffIncludedFields holds the string denoting the diff_included_fields field in the database.
	FieldDiffIncludedFields = "diff_included_fields"
	// FieldDiffFloatTolerance holds the string denoting the diff_float_tolerance field in the database.
	FieldDiffFloatTolerance = "diff_float_tolerance"
	// EdgeRequests holds the string denoting the requests edge name in mutations.
	EdgeRequests = "requests"
	// Table holds the table name of the gate in the database.
	Table = "gates"
	// RequestsTable is the table that holds the requests relation/edge.
	RequestsTable = "requests"
	// RequestsInverseTable is the table name for the Request entity.
	// It exists in this package in order to avoid circular dependency with the "request" package.
	RequestsInverseTable = "requests"
	// RequestsColumn is the table column denoting the requests relation/edge.
	RequestsColumn = "gate_id"
)

// Columns holds all SQL columns for gate fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldLiveURL,
	FieldShadowURL,
	FieldCreatedAt,
	FieldDiffIgnoredFields,
	FieldDiffIncludedFields,
	FieldDiffFloatTolerance,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// LiveURLValidator is a validator for the "live_url" field. It is called by the builders before save.
	LiveURLValidator func(string) error
	// ShadowURLValidator is a validator for the "shadow_url" field. It is called by the builders before save.
	ShadowURLValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Gate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLiveURL orders the results by the live_url field.
func ByLiveURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLiveURL, opts...).ToFunc()
}

// ByShadowURL orders the results by the shadow_url field.
func ByShadowURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShadowURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDiffFloatTolerance orders the results by the diff_float_tolerance field.
func ByDiffFloatTolerance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiffFloatTolerance, opts...).ToFunc()
}

// ByRequestsCount orders the results by requests count.
func ByRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRequestsStep(), opts...)
	}
}

// ByRequests orders the results by requests terms.
func ByRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RequestsTable, RequestsColumn),
	)
}
