// Code generated by ent, DO NOT EDIT.

package gate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Gate {
	return predicate.Gate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Gate {
	return predicate.Gate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Gate {
	return predicate.Gate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Gate {
	return predicate.Gate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Gate {
	return predicate.Gate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Gate {
	return predicate.Gate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Gate {
	return predicate.Gate(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldName, v))
}

// LiveURL applies equality check predicate on the "live_url" field. It's identical to LiveURLEQ.
func LiveURL(v string) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldLiveURL, v))
}

// ShadowURL applies equality check predicate on the "shadow_url" field. It's identical to ShadowURLEQ.
func ShadowURL(v string) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldShadowURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Gate {
	return predicate.Gate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Gate {
	return predicate.Gate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Gate {
	return predicate.Gate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Gate {
	return predicate.Gate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Gate {
	return predicate.Gate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Gate {
	return predicate.Gate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Gate {
	return predicate.Gate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Gate {
	return predicate.Gate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Gate {
	return predicate.Gate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Gate {
	return predicate.Gate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Gate {
	return predicate.Gate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Gate {
	return predicate.Gate(sql.FieldContainsFold(FieldName, v))
}

// LiveURLEQ applies the EQ predicate on the "live_url" field.
func LiveURLEQ(v string) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldLiveURL, v))
}

// LiveURLNEQ applies the NEQ predicate on the "live_url" field.
func LiveURLNEQ(v string) predicate.Gate {
	return predicate.Gate(sql.FieldNEQ(FieldLiveURL, v))
}

// LiveURLIn applies the In predicate on the "live_url" field.
func LiveURLIn(vs ...string) predicate.Gate {
	return predicate.Gate(sql.FieldIn(FieldLiveURL, vs...))
}

// LiveURLNotIn applies the NotIn predicate on the "live_url" field.
func LiveURLNotIn(vs ...string) predicate.Gate {
	return predicate.Gate(sql.FieldNotIn(FieldLiveURL, vs...))
}

// LiveURLGT applies the GT predicate on the "live_url" field.
func LiveURLGT(v string) predicate.Gate {
	return predicate.Gate(sql.FieldGT(FieldLiveURL, v))
}

// LiveURLGTE applies the GTE predicate on the "live_url" field.
func LiveURLGTE(v string) predicate.Gate {
	return predicate.Gate(sql.FieldGTE(FieldLiveURL, v))
}

// LiveURLLT applies the LT predicate on the "live_url" field.
func LiveURLLT(v string) predicate.Gate {
	return predicate.Gate(sql.FieldLT(FieldLiveURL, v))
}

// LiveURLLTE applies the LTE predicate on the "live_url" field.
func LiveURLLTE(v string) predicate.Gate {
	return predicate.Gate(sql.FieldLTE(FieldLiveURL, v))
}

// LiveURLContains applies the Contains predicate on the "live_url" field.
func LiveURLContains(v string) predicate.Gate {
	return predicate.Gate(sql.FieldContains(FieldLiveURL, v))
}

// LiveURLHasPrefix applies the HasPrefix predicate on the "live_url" field.
func LiveURLHasPrefix(v string) predicate.Gate {
	return predicate.Gate(sql.FieldHasPrefix(FieldLiveURL, v))
}

// LiveURLHasSuffix applies the HasSuffix predicate on the "live_url" field.
func LiveURLHasSuffix(v string) predicate.Gate {
	return predicate.Gate(sql.FieldHasSuffix(FieldLiveURL, v))
}

// LiveURLEqualFold applies the EqualFold predicate on the "live_url" field.
func LiveURLEqualFold(v string) predicate.Gate {
	return predicate.Gate(sql.FieldEqualFold(FieldLiveURL, v))
}

// LiveURLContainsFold applies the ContainsFold predicate on the "live_url" field.
func LiveURLContainsFold(v string) predicate.Gate {
	return predicate.Gate(sql.FieldContainsFold(FieldLiveURL, v))
}

// ShadowURLEQ applies the EQ predicate on the "shadow_url" field.
func ShadowURLEQ(v string) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldShadowURL, v))
}

// ShadowURLNEQ applies the NEQ predicate on the "shadow_url" field.
func ShadowURLNEQ(v string) predicate.Gate {
	return predicate.Gate(sql.FieldNEQ(FieldShadowURL, v))
}

// ShadowURLIn applies the In predicate on the "shadow_url" field.
func ShadowURLIn(vs ...string) predicate.Gate {
	return predicate.Gate(sql.FieldIn(FieldShadowURL, vs...))
}

// ShadowURLNotIn applies the NotIn predicate on the "shadow_url" field.
func ShadowURLNotIn(vs ...string) predicate.Gate {
	return predicate.Gate(sql.FieldNotIn(FieldShadowURL, vs...))
}

// ShadowURLGT applies the GT predicate on the "shadow_url" field.
func ShadowURLGT(v string) predicate.Gate {
	return predicate.Gate(sql.FieldGT(FieldShadowURL, v))
}

// ShadowURLGTE applies the GTE predicate on the "shadow_url" field.
func ShadowURLGTE(v string) predicate.Gate {
	return predicate.Gate(sql.FieldGTE(FieldShadowURL, v))
}

// ShadowURLLT applies the LT predicate on the "shadow_url" field.
func ShadowURLLT(v string) predicate.Gate {
	return predicate.Gate(sql.FieldLT(FieldShadowURL, v))
}

// ShadowURLLTE applies the LTE predicate on the "shadow_url" field.
func ShadowURLLTE(v string) predicate.Gate {
	return predicate.Gate(sql.FieldLTE(FieldShadowURL, v))
}

// ShadowURLContains applies the Contains predicate on the "shadow_url" field.
func ShadowURLContains(v string) predicate.Gate {
	return predicate.Gate(sql.FieldContains(FieldShadowURL, v))
}

// ShadowURLHasPrefix applies the HasPrefix predicate on the "shadow_url" field.
func ShadowURLHasPrefix(v string) predicate.Gate {
	return predicate.Gate(sql.FieldHasPrefix(FieldShadowURL, v))
}

// ShadowURLHasSuffix applies the HasSuffix predicate on the "shadow_url" field.
func ShadowURLHasSuffix(v string) predicate.Gate {
	return predicate.Gate(sql.FieldHasSuffix(FieldShadowURL, v))
}

// ShadowURLEqualFold applies the EqualFold predicate on the "shadow_url" field.
func ShadowURLEqualFold(v string) predicate.Gate {
	return predicate.Gate(sql.FieldEqualFold(FieldShadowURL, v))
}

// ShadowURLContainsFold applies the ContainsFold predicate on the "shadow_url" field.
func ShadowURLContainsFold(v string) predicate.Gate {
	return predicate.Gate(sql.FieldContainsFold(FieldShadowURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Gate {
	return predicate.Gate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Gate {
	return predicate.Gate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Gate {
	return predicate.Gate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Gate {
	return predicate.Gate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Gate {
	return predicate.Gate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Gate {
	return predicate.Gate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Gate {
	return predicate.Gate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Gate {
	return predicate.Gate(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRequests applies the HasEdge predicate on the "requests" edge.
func HasRequests() predicate.Gate {
	return predicate.Gate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RequestsTable, RequestsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestsWith applies the HasEdge predicate on the "requests" edge with a given conditions (other predicates).
func HasRequestsWith(preds ...predicate.Request) predicate.Gate {
	return predicate.Gate(func(s *sql.Selector) {
		step := newRequestsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Gate) predicate.Gate {
	return predicate.Gate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Gate) predicate.Gate {
	return predicate.Gate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Gate) predicate.Gate {
	return predicate.Gate(sql.NotPredicates(p))
}
