// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pedrobarco/mroki/internal/domain/diffing (interfaces: GateRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_gate_repository.go -package=mocks github.com/pedrobarco/mroki/internal/domain/diffing GateRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	diffing "github.com/pedrobarco/mroki/internal/domain/diffing"
	pagination "github.com/pedrobarco/mroki/internal/domain/pagination"
	gomock "go.uber.org/mock/gomock"
)

// MockGateRepository is a mock of GateRepository interface.
type MockGateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGateRepositoryMockRecorder
	isgomock struct{}
}

// MockGateRepositoryMockRecorder is the mock recorder for MockGateRepository.
type MockGateRepositoryMockRecorder struct {
	mock *MockGateRepository
}

// NewMockGateRepository creates a new mock instance.
func NewMockGateRepository(ctrl *gomock.Controller) *MockGateRepository {
	mock := &MockGateRepository{ctrl: ctrl}
	mock.recorder = &MockGateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateRepository) EXPECT() *MockGateRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockGateRepository) GetAll(ctx context.Context, params *pagination.Params) (*pagination.PagedResult[*diffing.Gate], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, params)
	ret0, _ := ret[0].(*pagination.PagedResult[*diffing.Gate])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockGateRepositoryMockRecorder) GetAll(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockGateRepository)(nil).GetAll), ctx, params)
}

// GetByID mocks base method.
func (m *MockGateRepository) GetByID(ctx context.Context, id diffing.GateID) (*diffing.Gate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*diffing.Gate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGateRepository)(nil).GetByID), ctx, id)
}

// Save mocks base method.
func (m *MockGateRepository) Save(ctx context.Context, gate *diffing.Gate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, gate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGateRepositoryMockRecorder) Save(ctx, gate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGateRepository)(nil).Save), ctx, gate)
}
