// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pedrobarco/mroki/internal/domain/diffing (interfaces: RequestRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_request_repository.go -package=mocks github.com/pedrobarco/mroki/internal/domain/diffing RequestRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	diffing "github.com/pedrobarco/mroki/internal/domain/diffing"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestRepository is a mock of RequestRepository interface.
type MockRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockRequestRepositoryMockRecorder is the mock recorder for MockRequestRepository.
type MockRequestRepositoryMockRecorder struct {
	mock *MockRequestRepository
}

// NewMockRequestRepository creates a new mock instance.
func NewMockRequestRepository(ctrl *gomock.Controller) *MockRequestRepository {
	mock := &MockRequestRepository{ctrl: ctrl}
	mock.recorder = &MockRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestRepository) EXPECT() *MockRequestRepositoryMockRecorder {
	return m.recorder
}

// GetAllByGateID mocks base method.
func (m *MockRequestRepository) GetAllByGateID(ctx context.Context, gateID diffing.GateID) ([]*diffing.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByGateID", ctx, gateID)
	ret0, _ := ret[0].([]*diffing.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByGateID indicates an expected call of GetAllByGateID.
func (mr *MockRequestRepositoryMockRecorder) GetAllByGateID(ctx, gateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByGateID", reflect.TypeOf((*MockRequestRepository)(nil).GetAllByGateID), ctx, gateID)
}

// GetByID mocks base method.
func (m *MockRequestRepository) GetByID(ctx context.Context, id diffing.RequestID, gateID diffing.GateID) (*diffing.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, gateID)
	ret0, _ := ret[0].(*diffing.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRequestRepositoryMockRecorder) GetByID(ctx, id, gateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRequestRepository)(nil).GetByID), ctx, id, gateID)
}

// Save mocks base method.
func (m *MockRequestRepository) Save(ctx context.Context, request *diffing.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRequestRepositoryMockRecorder) Save(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRequestRepository)(nil).Save), ctx, request)
}
