// Code generated by ent, DO NOT EDIT.

package diff

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the diff type in the database.
	Label = "diff"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldFromResponseID holds the string denoting the from_response_id field in the database.
	FieldFromResponseID = "from_response_id"
	// FieldToResponseID holds the string denoting the to_response_id field in the database.
	FieldToResponseID = "to_response_id"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeRequest holds the string denoting the request edge name in mutations.
	EdgeRequest = "request"
	// EdgeFromResponse holds the string denoting the from_response edge name in mutations.
	EdgeFromResponse = "from_response"
	// EdgeToResponse holds the string denoting the to_response edge name in mutations.
	EdgeToResponse = "to_response"
	// Table holds the table name of the diff in the database.
	Table = "diffs"
	// RequestTable is the table that holds the request relation/edge.
	RequestTable = "diffs"
	// RequestInverseTable is the table name for the Request entity.
	// It exists in this package in order to avoid circular dependency with the "request" package.
	RequestInverseTable = "requests"
	// RequestColumn is the table column denoting the request relation/edge.
	RequestColumn = "request_id"
	// FromResponseTable is the table that holds the from_response relation/edge.
	FromResponseTable = "diffs"
	// FromResponseInverseTable is the table name for the Response entity.
	// It exists in this package in order to avoid circular dependency with the "response" package.
	FromResponseInverseTable = "responses"
	// FromResponseColumn is the table column denoting the from_response relation/edge.
	FromResponseColumn = "from_response_id"
	// ToResponseTable is the table that holds the to_response relation/edge.
	ToResponseTable = "diffs"
	// ToResponseInverseTable is the table name for the Response entity.
	// It exists in this package in order to avoid circular dependency with the "response" package.
	ToResponseInverseTable = "responses"
	// ToResponseColumn is the table column denoting the to_response relation/edge.
	ToResponseColumn = "to_response_id"
)

// Columns holds all SQL columns for diff fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldFromResponseID,
	FieldToResponseID,
	FieldContent,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Diff queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByFromResponseID orders the results by the from_response_id field.
func ByFromResponseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromResponseID, opts...).ToFunc()
}

// ByToResponseID orders the results by the to_response_id field.
func ByToResponseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToResponseID, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRequestField orders the results by request field.
func ByRequestField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRequestStep(), sql.OrderByField(field, opts...))
	}
}

// ByFromResponseField orders the results by from_response field.
func ByFromResponseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFromResponseStep(), sql.OrderByField(field, opts...))
	}
}

// ByToResponseField orders the results by to_response field.
func ByToResponseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newToResponseStep(), sql.OrderByField(field, opts...))
	}
}
func newRequestStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RequestInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, RequestTable, RequestColumn),
	)
}
func newFromResponseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FromResponseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FromResponseTable, FromResponseColumn),
	)
}
func newToResponseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ToResponseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ToResponseTable, ToResponseColumn),
	)
}
