// Code generated by ent, DO NOT EDIT.

package diff

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldRequestID, v))
}

// FromResponseID applies equality check predicate on the "from_response_id" field. It's identical to FromResponseIDEQ.
func FromResponseID(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldFromResponseID, v))
}

// ToResponseID applies equality check predicate on the "to_response_id" field. It's identical to ToResponseIDEQ.
func ToResponseID(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldToResponseID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldContent, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldRequestID, vs...))
}

// FromResponseIDEQ applies the EQ predicate on the "from_response_id" field.
func FromResponseIDEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldFromResponseID, v))
}

// FromResponseIDNEQ applies the NEQ predicate on the "from_response_id" field.
func FromResponseIDNEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldFromResponseID, v))
}

// FromResponseIDIn applies the In predicate on the "from_response_id" field.
func FromResponseIDIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldFromResponseID, vs...))
}

// FromResponseIDNotIn applies the NotIn predicate on the "from_response_id" field.
func FromResponseIDNotIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldFromResponseID, vs...))
}

// FromResponseIDGT applies the GT predicate on the "from_response_id" field.
func FromResponseIDGT(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldGT(FieldFromResponseID, v))
}

// FromResponseIDGTE applies the GTE predicate on the "from_response_id" field.
func FromResponseIDGTE(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldGTE(FieldFromResponseID, v))
}

// FromResponseIDLT applies the LT predicate on the "from_response_id" field.
func FromResponseIDLT(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldLT(FieldFromResponseID, v))
}

// FromResponseIDLTE applies the LTE predicate on the "from_response_id" field.
func FromResponseIDLTE(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldLTE(FieldFromResponseID, v))
}

// ToResponseIDEQ applies the EQ predicate on the "to_response_id" field.
func ToResponseIDEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldToResponseID, v))
}

// ToResponseIDNEQ applies the NEQ predicate on the "to_response_id" field.
func ToResponseIDNEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldToResponseID, v))
}

// ToResponseIDIn applies the In predicate on the "to_response_id" field.
func ToResponseIDIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldToResponseID, vs...))
}

// ToResponseIDNotIn applies the NotIn predicate on the "to_response_id" field.
func ToResponseIDNotIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldToResponseID, vs...))
}

// ToResponseIDGT applies the GT predicate on the "to_response_id" field.
func ToResponseIDGT(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldGT(FieldToResponseID, v))
}

// ToResponseIDGTE applies the GTE predicate on the "to_response_id" field.
func ToResponseIDGTE(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldGTE(FieldToResponseID, v))
}

// ToResponseIDLT applies the LT predicate on the "to_response_id" field.
func ToResponseIDLT(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldLT(FieldToResponseID, v))
}

// ToResponseIDLTE applies the LTE predicate on the "to_response_id" field.
func ToResponseIDLTE(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldLTE(FieldToResponseID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Diff {
	return predicate.Diff(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Diff {
	return predicate.Diff(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Diff {
	return predicate.Diff(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Diff {
	return predicate.Diff(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Diff {
	return predicate.Diff(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Diff {
	return predicate.Diff(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Diff {
	return predicate.Diff(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Diff {
	return predicate.Diff(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Diff {
	return predicate.Diff(sql.FieldContainsFold(FieldContent, v))
}

// HasRequest applies the HasEdge predicate on the "request" edge.
func HasRequest() predicate.Diff {
	return predicate.Diff(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, RequestTable, RequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestWith applies the HasEdge predicate on the "request" edge with a given conditions (other predicates).
func HasRequestWith(preds ...predicate.Request) predicate.Diff {
	return predicate.Diff(func(s *sql.Selector) {
		step := newRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Diff) predicate.Diff {
	return predicate.Diff(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Diff) predicate.Diff {
	return predicate.Diff(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Diff) predicate.Diff {
	return predicate.Diff(sql.NotPredicates(p))
}
