// Code generated by ent, DO NOT EDIT.

package entdiff

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldRequestID, v))
}

// FromResponseID applies equality check predicate on the "from_response_id" field. It's identical to FromResponseIDEQ.
func FromResponseID(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldFromResponseID, v))
}

// ToResponseID applies equality check predicate on the "to_response_id" field. It's identical to ToResponseIDEQ.
func ToResponseID(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldToResponseID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldCreatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldRequestID, vs...))
}

// FromResponseIDEQ applies the EQ predicate on the "from_response_id" field.
func FromResponseIDEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldFromResponseID, v))
}

// FromResponseIDNEQ applies the NEQ predicate on the "from_response_id" field.
func FromResponseIDNEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldFromResponseID, v))
}

// FromResponseIDIn applies the In predicate on the "from_response_id" field.
func FromResponseIDIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldFromResponseID, vs...))
}

// FromResponseIDNotIn applies the NotIn predicate on the "from_response_id" field.
func FromResponseIDNotIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldFromResponseID, vs...))
}

// ToResponseIDEQ applies the EQ predicate on the "to_response_id" field.
func ToResponseIDEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldToResponseID, v))
}

// ToResponseIDNEQ applies the NEQ predicate on the "to_response_id" field.
func ToResponseIDNEQ(v uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldToResponseID, v))
}

// ToResponseIDIn applies the In predicate on the "to_response_id" field.
func ToResponseIDIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldToResponseID, vs...))
}

// ToResponseIDNotIn applies the NotIn predicate on the "to_response_id" field.
func ToResponseIDNotIn(vs ...uuid.UUID) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldToResponseID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Diff {
	return predicate.Diff(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Diff {
	return predicate.Diff(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Diff {
	return predicate.Diff(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Diff {
	return predicate.Diff(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Diff {
	return predicate.Diff(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Diff {
	return predicate.Diff(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Diff {
	return predicate.Diff(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Diff {
	return predicate.Diff(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRequest applies the HasEdge predicate on the "request" edge.
func HasRequest() predicate.Diff {
	return predicate.Diff(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, RequestTable, RequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestWith applies the HasEdge predicate on the "request" edge with a given conditions (other predicates).
func HasRequestWith(preds ...predicate.Request) predicate.Diff {
	return predicate.Diff(func(s *sql.Selector) {
		step := newRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFromResponse applies the HasEdge predicate on the "from_response" edge.
func HasFromResponse() predicate.Diff {
	return predicate.Diff(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FromResponseTable, FromResponseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFromResponseWith applies the HasEdge predicate on the "from_response" edge with a given conditions (other predicates).
func HasFromResponseWith(preds ...predicate.Response) predicate.Diff {
	return predicate.Diff(func(s *sql.Selector) {
		step := newFromResponseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasToResponse applies the HasEdge predicate on the "to_response" edge.
func HasToResponse() predicate.Diff {
	return predicate.Diff(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ToResponseTable, ToResponseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasToResponseWith applies the HasEdge predicate on the "to_response" edge with a given conditions (other predicates).
func HasToResponseWith(preds ...predicate.Response) predicate.Diff {
	return predicate.Diff(func(s *sql.Selector) {
		step := newToResponseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Diff) predicate.Diff {
	return predicate.Diff(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Diff) predicate.Diff {
	return predicate.Diff(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Diff) predicate.Diff {
	return predicate.Diff(sql.NotPredicates(p))
}
