// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Gate struct {
	ID        pgtype.UUID
	LiveUrl   pgtype.Text
	ShadowUrl pgtype.Text
}
