// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Diff struct {
	ID             pgtype.UUID
	RequestID      pgtype.UUID
	FromResponseID pgtype.UUID
	ToResponseID   pgtype.UUID
	Content        []byte
}

type Gate struct {
	ID        pgtype.UUID
	LiveUrl   pgtype.Text
	ShadowUrl pgtype.Text
}

type Request struct {
	ID        pgtype.UUID
	GateID    pgtype.UUID
	AgentID   pgtype.Text
	Method    pgtype.Text
	Path      pgtype.Text
	Headers   []byte
	Body      []byte
	CreatedAt pgtype.Timestamptz
}

type Response struct {
	ID         pgtype.UUID
	RequestID  pgtype.UUID
	Type       pgtype.Text
	StatusCode pgtype.Int4
	Headers    []byte
	Body       []byte
	CreatedAt  pgtype.Timestamptz
}
