// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllGates = `-- name: GetAllGates :many
SELECT id, live_url, shadow_url
FROM gates
`

func (q *Queries) GetAllGates(ctx context.Context) ([]Gate, error) {
	rows, err := q.db.Query(ctx, getAllGates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gate
	for rows.Next() {
		var i Gate
		if err := rows.Scan(&i.ID, &i.LiveUrl, &i.ShadowUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGateByID = `-- name: GetGateByID :one
SELECT id, live_url, shadow_url
FROM gates
WHERE id = $1
`

func (q *Queries) GetGateByID(ctx context.Context, id pgtype.UUID) (Gate, error) {
	row := q.db.QueryRow(ctx, getGateByID, id)
	var i Gate
	err := row.Scan(&i.ID, &i.LiveUrl, &i.ShadowUrl)
	return i, err
}

const saveGate = `-- name: SaveGate :exec
INSERT INTO gates (id, live_url, shadow_url)
VALUES ($1, $2, $3)
`

type SaveGateParams struct {
	ID        pgtype.UUID
	LiveUrl   pgtype.Text
	ShadowUrl pgtype.Text
}

func (q *Queries) SaveGate(ctx context.Context, arg SaveGateParams) error {
	_, err := q.db.Exec(ctx, saveGate, arg.ID, arg.LiveUrl, arg.ShadowUrl)
	return err
}
