{{- if and .Values.migration.enabled (or .Values.existingSecret .Values.database.passwordSecret) }}
{{- $jobName := printf "%s-migrate" (include "api.fullname" .) -}}
{{- if not .Values.migration.asHook -}}
{{- $suffix := .Values.migration.nameSuffix | default .Chart.AppVersion -}}
{{- if $suffix -}}
{{- $jobName = printf "%s-migrate-%s" (include "api.fullname" .) $suffix | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-migrator
  {{- if .Values.migration.asHook }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  {{- end }}
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  {{- if not (kindIs "invalid" .Values.migration.ttlSecondsAfterFinished) }}
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: db-migrator
    spec:
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      restartPolicy: Never
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: db-migrator
          image: {{ include "api.migrationImage" . }}
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - "--url"
            - "$(MROKI_APP_DATABASE_URL)"
            {{- with .Values.migration.baseline }}
            - "--baseline"
            - {{ . | quote }}
            {{- end }}
          env:
            {{- include "api.databaseEnv" . | nindent 12 }}
          {{- with .Values.migration.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
