// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Diff struct {
	RequestID      pgtype.UUID
	FromResponseID pgtype.UUID
	ToResponseID   pgtype.UUID
	Content        string
}

type Gate struct {
	ID        pgtype.UUID
	LiveUrl   string
	ShadowUrl string
}

type Request struct {
	ID        pgtype.UUID
	GateID    pgtype.UUID
	AgentID   pgtype.Text
	Method    string
	Path      string
	Headers   []byte
	Body      []byte
	CreatedAt pgtype.Timestamptz
}

type Response struct {
	ID         pgtype.UUID
	RequestID  pgtype.UUID
	Type       string
	StatusCode int32
	Headers    []byte
	Body       []byte
	CreatedAt  pgtype.Timestamptz
}
