// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGates = `-- name: CountGates :one
SELECT COUNT(*) FROM gates
`

func (q *Queries) CountGates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByGateID = `-- name: CountRequestsByGateID :one
SELECT COUNT(*) FROM requests WHERE gate_id = $1
`

func (q *Queries) CountRequestsByGateID(ctx context.Context, gateID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByGateID, gateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllGates = `-- name: GetAllGates :many
SELECT id, live_url, shadow_url
FROM gates
ORDER BY id
LIMIT $2
OFFSET $1
`

type GetAllGatesParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetAllGates(ctx context.Context, arg GetAllGatesParams) ([]Gate, error) {
	rows, err := q.db.Query(ctx, getAllGates, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gate
	for rows.Next() {
		var i Gate
		if err := rows.Scan(&i.ID, &i.LiveUrl, &i.ShadowUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRequestsByGateID = `-- name: GetAllRequestsByGateID :many
SELECT id, gate_id, agent_id, method, path, headers, body, created_at
FROM requests
WHERE gate_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type GetAllRequestsByGateIDParams struct {
	GateID pgtype.UUID
	Offset int32
	Limit  int32
}

func (q *Queries) GetAllRequestsByGateID(ctx context.Context, arg GetAllRequestsByGateIDParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, getAllRequestsByGateID, arg.GateID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.GateID,
			&i.AgentID,
			&i.Method,
			&i.Path,
			&i.Headers,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGateByID = `-- name: GetGateByID :one
SELECT id, live_url, shadow_url
FROM gates
WHERE id = $1
`

func (q *Queries) GetGateByID(ctx context.Context, id pgtype.UUID) (Gate, error) {
	row := q.db.QueryRow(ctx, getGateByID, id)
	var i Gate
	err := row.Scan(&i.ID, &i.LiveUrl, &i.ShadowUrl)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :many
SELECT
  req.id as request_id,
  req.gate_id as request_gate_id,
  req.agent_id as request_agent_id,
  req.method as request_method,
  req.path as request_path,
  req.headers as request_headers,
  req.body as request_body,
  req.created_at as request_created_at,

  resp.id AS response_id,
  resp.type AS response_type,
  resp.status_code AS response_status_code,
  resp.headers AS response_headers,
  resp.body AS response_body,
  resp.created_at AS response_created_at,

  diff.from_response_id AS diff_from_response_id,
  diff.to_response_id AS diff_to_response_id,
  diff.content AS diff_content

FROM requests req
LEFT JOIN responses resp ON resp.request_id = req.id
LEFT JOIN diffs diff ON diff.request_id = req.id
WHERE req.gate_id = $1 AND req.id = $2
`

type GetRequestByIDParams struct {
	GateID pgtype.UUID
	ID     pgtype.UUID
}

type GetRequestByIDRow struct {
	RequestID          pgtype.UUID
	RequestGateID      pgtype.UUID
	RequestAgentID     pgtype.Text
	RequestMethod      string
	RequestPath        string
	RequestHeaders     []byte
	RequestBody        []byte
	RequestCreatedAt   pgtype.Timestamptz
	ResponseID         pgtype.UUID
	ResponseType       pgtype.Text
	ResponseStatusCode pgtype.Int4
	ResponseHeaders    []byte
	ResponseBody       []byte
	ResponseCreatedAt  pgtype.Timestamptz
	DiffFromResponseID pgtype.UUID
	DiffToResponseID   pgtype.UUID
	DiffContent        pgtype.Text
}

func (q *Queries) GetRequestByID(ctx context.Context, arg GetRequestByIDParams) ([]GetRequestByIDRow, error) {
	rows, err := q.db.Query(ctx, getRequestByID, arg.GateID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRequestByIDRow
	for rows.Next() {
		var i GetRequestByIDRow
		if err := rows.Scan(
			&i.RequestID,
			&i.RequestGateID,
			&i.RequestAgentID,
			&i.RequestMethod,
			&i.RequestPath,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.RequestCreatedAt,
			&i.ResponseID,
			&i.ResponseType,
			&i.ResponseStatusCode,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.ResponseCreatedAt,
			&i.DiffFromResponseID,
			&i.DiffToResponseID,
			&i.DiffContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDiff = `-- name: SaveDiff :exec
INSERT INTO diffs (request_id, from_response_id, to_response_id, content)
VALUES ($1, $2, $3, $4)
`

type SaveDiffParams struct {
	RequestID      pgtype.UUID
	FromResponseID pgtype.UUID
	ToResponseID   pgtype.UUID
	Content        string
}

func (q *Queries) SaveDiff(ctx context.Context, arg SaveDiffParams) error {
	_, err := q.db.Exec(ctx, saveDiff,
		arg.RequestID,
		arg.FromResponseID,
		arg.ToResponseID,
		arg.Content,
	)
	return err
}

const saveGate = `-- name: SaveGate :exec
INSERT INTO gates (id, live_url, shadow_url)
VALUES ($1, $2, $3)
`

type SaveGateParams struct {
	ID        pgtype.UUID
	LiveUrl   string
	ShadowUrl string
}

func (q *Queries) SaveGate(ctx context.Context, arg SaveGateParams) error {
	_, err := q.db.Exec(ctx, saveGate, arg.ID, arg.LiveUrl, arg.ShadowUrl)
	return err
}

const saveRequest = `-- name: SaveRequest :exec
INSERT INTO requests (id, gate_id, agent_id, method, path, headers, body, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SaveRequestParams struct {
	ID        pgtype.UUID
	GateID    pgtype.UUID
	AgentID   pgtype.Text
	Method    string
	Path      string
	Headers   []byte
	Body      []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) SaveRequest(ctx context.Context, arg SaveRequestParams) error {
	_, err := q.db.Exec(ctx, saveRequest,
		arg.ID,
		arg.GateID,
		arg.AgentID,
		arg.Method,
		arg.Path,
		arg.Headers,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const saveResponse = `-- name: SaveResponse :exec
INSERT INTO responses (id, request_id, type, status_code, headers, body, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type SaveResponseParams struct {
	ID         pgtype.UUID
	RequestID  pgtype.UUID
	Type       string
	StatusCode int32
	Headers    []byte
	Body       []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) SaveResponse(ctx context.Context, arg SaveResponseParams) error {
	_, err := q.db.Exec(ctx, saveResponse,
		arg.ID,
		arg.RequestID,
		arg.Type,
		arg.StatusCode,
		arg.Headers,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}
