// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DiffsColumns holds the columns for the "diffs" table.
	DiffsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "content", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "request_id", Type: field.TypeUUID, Unique: true},
		{Name: "from_response_id", Type: field.TypeUUID},
		{Name: "to_response_id", Type: field.TypeUUID},
	}
	// DiffsTable holds the schema information for the "diffs" table.
	DiffsTable = &schema.Table{
		Name:       "diffs",
		Columns:    DiffsColumns,
		PrimaryKey: []*schema.Column{DiffsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "diffs_requests_diff",
				Columns:    []*schema.Column{DiffsColumns[3]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "diffs_responses_diffs_from",
				Columns:    []*schema.Column{DiffsColumns[4]},
				RefColumns: []*schema.Column{ResponsesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "diffs_responses_diffs_to",
				Columns:    []*schema.Column{DiffsColumns[5]},
				RefColumns: []*schema.Column{ResponsesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// GatesColumns holds the columns for the "gates" table.
	GatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "live_url", Type: field.TypeString},
		{Name: "shadow_url", Type: field.TypeString},
	}
	// GatesTable holds the schema information for the "gates" table.
	GatesTable = &schema.Table{
		Name:       "gates",
		Columns:    GatesColumns,
		PrimaryKey: []*schema.Column{GatesColumns[0]},
	}
	// RequestsColumns holds the columns for the "requests" table.
	RequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "agent_id", Type: field.TypeString, Nullable: true},
		{Name: "method", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "headers", Type: field.TypeJSON, Nullable: true},
		{Name: "body", Type: field.TypeBytes, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "gate_id", Type: field.TypeUUID},
	}
	// RequestsTable holds the schema information for the "requests" table.
	RequestsTable = &schema.Table{
		Name:       "requests",
		Columns:    RequestsColumns,
		PrimaryKey: []*schema.Column{RequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "requests_gates_requests",
				Columns:    []*schema.Column{RequestsColumns[7]},
				RefColumns: []*schema.Column{GatesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "request_gate_id",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[7]},
			},
			{
				Name:    "request_gate_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[7], RequestsColumns[6]},
			},
			{
				Name:    "request_gate_id_method",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[7], RequestsColumns[2]},
			},
			{
				Name:    "request_gate_id_path",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[7], RequestsColumns[3]},
			},
			{
				Name:    "request_agent_id",
				Unique:  false,
				Columns: []*schema.Column{RequestsColumns[1]},
			},
		},
	}
	// ResponsesColumns holds the columns for the "responses" table.
	ResponsesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "type", Type: field.TypeString},
		{Name: "status_code", Type: field.TypeInt32},
		{Name: "headers", Type: field.TypeJSON, Nullable: true},
		{Name: "body", Type: field.TypeBytes, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "request_id", Type: field.TypeUUID},
	}
	// ResponsesTable holds the schema information for the "responses" table.
	ResponsesTable = &schema.Table{
		Name:       "responses",
		Columns:    ResponsesColumns,
		PrimaryKey: []*schema.Column{ResponsesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "responses_requests_responses",
				Columns:    []*schema.Column{ResponsesColumns[6]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "response_request_id",
				Unique:  false,
				Columns: []*schema.Column{ResponsesColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DiffsTable,
		GatesTable,
		RequestsTable,
		ResponsesTable,
	}
)

func init() {
	DiffsTable.ForeignKeys[0].RefTable = RequestsTable
	DiffsTable.ForeignKeys[1].RefTable = ResponsesTable
	DiffsTable.ForeignKeys[2].RefTable = ResponsesTable
	RequestsTable.ForeignKeys[0].RefTable = GatesTable
	ResponsesTable.ForeignKeys[0].RefTable = RequestsTable
}
