// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/request"
)

// Diff is the model entity for the Diff schema.
type Diff struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID uuid.UUID `json:"request_id,omitempty"`
	// FromResponseID holds the value of the "from_response_id" field.
	FromResponseID uuid.UUID `json:"from_response_id,omitempty"`
	// ToResponseID holds the value of the "to_response_id" field.
	ToResponseID uuid.UUID `json:"to_response_id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DiffQuery when eager-loading is set.
	Edges        DiffEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DiffEdges holds the relations/edges for other nodes in the graph.
type DiffEdges struct {
	// Request holds the value of the request edge.
	Request *Request `json:"request,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RequestOrErr returns the Request value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DiffEdges) RequestOrErr() (*Request, error) {
	if e.Request != nil {
		return e.Request, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: request.Label}
	}
	return nil, &NotLoadedError{edge: "request"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Diff) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case diff.FieldContent:
			values[i] = new(sql.NullString)
		case diff.FieldID, diff.FieldRequestID, diff.FieldFromResponseID, diff.FieldToResponseID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Diff fields.
func (_m *Diff) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case diff.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case diff.FieldRequestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value != nil {
				_m.RequestID = *value
			}
		case diff.FieldFromResponseID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field from_response_id", values[i])
			} else if value != nil {
				_m.FromResponseID = *value
			}
		case diff.FieldToResponseID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field to_response_id", values[i])
			} else if value != nil {
				_m.ToResponseID = *value
			}
		case diff.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Diff.
// This includes values selected through modifiers, order, etc.
func (_m *Diff) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequest queries the "request" edge of the Diff entity.
func (_m *Diff) QueryRequest() *RequestQuery {
	return NewDiffClient(_m.config).QueryRequest(_m)
}

// Update returns a builder for updating this Diff.
// Note that you need to call Diff.Unwrap() before calling this method if this Diff
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Diff) Update() *DiffUpdateOne {
	return NewDiffClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Diff entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Diff) Unwrap() *Diff {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Diff is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Diff) String() string {
	var builder strings.Builder
	builder.WriteString("Diff(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestID))
	builder.WriteString(", ")
	builder.WriteString("from_response_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FromResponseID))
	builder.WriteString(", ")
	builder.WriteString("to_response_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToResponseID))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteByte(')')
	return builder.String()
}

// Diffs is a parsable slice of Diff.
type Diffs []*Diff
