// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/predicate"
	"github.com/pedrobarco/mroki/ent/request"
)

// DiffUpdate is the builder for updating Diff entities.
type DiffUpdate struct {
	config
	hooks    []Hook
	mutation *DiffMutation
}

// Where appends a list predicates to the DiffUpdate builder.
func (_u *DiffUpdate) Where(ps ...predicate.Diff) *DiffUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *DiffUpdate) SetRequestID(v uuid.UUID) *DiffUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *DiffUpdate) SetNillableRequestID(v *uuid.UUID) *DiffUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetFromResponseID sets the "from_response_id" field.
func (_u *DiffUpdate) SetFromResponseID(v uuid.UUID) *DiffUpdate {
	_u.mutation.SetFromResponseID(v)
	return _u
}

// SetNillableFromResponseID sets the "from_response_id" field if the given value is not nil.
func (_u *DiffUpdate) SetNillableFromResponseID(v *uuid.UUID) *DiffUpdate {
	if v != nil {
		_u.SetFromResponseID(*v)
	}
	return _u
}

// SetToResponseID sets the "to_response_id" field.
func (_u *DiffUpdate) SetToResponseID(v uuid.UUID) *DiffUpdate {
	_u.mutation.SetToResponseID(v)
	return _u
}

// SetNillableToResponseID sets the "to_response_id" field if the given value is not nil.
func (_u *DiffUpdate) SetNillableToResponseID(v *uuid.UUID) *DiffUpdate {
	if v != nil {
		_u.SetToResponseID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *DiffUpdate) SetContent(v string) *DiffUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DiffUpdate) SetNillableContent(v *string) *DiffUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetRequest sets the "request" edge to the Request entity.
func (_u *DiffUpdate) SetRequest(v *Request) *DiffUpdate {
	return _u.SetRequestID(v.ID)
}

// Mutation returns the DiffMutation object of the builder.
func (_u *DiffUpdate) Mutation() *DiffMutation {
	return _u.mutation
}

// ClearRequest clears the "request" edge to the Request entity.
func (_u *DiffUpdate) ClearRequest() *DiffUpdate {
	_u.mutation.ClearRequest()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiffUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiffUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiffUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiffUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiffUpdate) check() error {
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Diff.request"`)
	}
	return nil
}

func (_u *DiffUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diff.Table, diff.Columns, sqlgraph.NewFieldSpec(diff.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FromResponseID(); ok {
		_spec.SetField(diff.FieldFromResponseID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ToResponseID(); ok {
		_spec.SetField(diff.FieldToResponseID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(diff.FieldContent, field.TypeString, value)
	}
	if _u.mutation.RequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   diff.RequestTable,
			Columns: []string{diff.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   diff.RequestTable,
			Columns: []string{diff.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diff.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiffUpdateOne is the builder for updating a single Diff entity.
type DiffUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiffMutation
}

// SetRequestID sets the "request_id" field.
func (_u *DiffUpdateOne) SetRequestID(v uuid.UUID) *DiffUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *DiffUpdateOne) SetNillableRequestID(v *uuid.UUID) *DiffUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetFromResponseID sets the "from_response_id" field.
func (_u *DiffUpdateOne) SetFromResponseID(v uuid.UUID) *DiffUpdateOne {
	_u.mutation.SetFromResponseID(v)
	return _u
}

// SetNillableFromResponseID sets the "from_response_id" field if the given value is not nil.
func (_u *DiffUpdateOne) SetNillableFromResponseID(v *uuid.UUID) *DiffUpdateOne {
	if v != nil {
		_u.SetFromResponseID(*v)
	}
	return _u
}

// SetToResponseID sets the "to_response_id" field.
func (_u *DiffUpdateOne) SetToResponseID(v uuid.UUID) *DiffUpdateOne {
	_u.mutation.SetToResponseID(v)
	return _u
}

// SetNillableToResponseID sets the "to_response_id" field if the given value is not nil.
func (_u *DiffUpdateOne) SetNillableToResponseID(v *uuid.UUID) *DiffUpdateOne {
	if v != nil {
		_u.SetToResponseID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *DiffUpdateOne) SetContent(v string) *DiffUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *DiffUpdateOne) SetNillableContent(v *string) *DiffUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetRequest sets the "request" edge to the Request entity.
func (_u *DiffUpdateOne) SetRequest(v *Request) *DiffUpdateOne {
	return _u.SetRequestID(v.ID)
}

// Mutation returns the DiffMutation object of the builder.
func (_u *DiffUpdateOne) Mutation() *DiffMutation {
	return _u.mutation
}

// ClearRequest clears the "request" edge to the Request entity.
func (_u *DiffUpdateOne) ClearRequest() *DiffUpdateOne {
	_u.mutation.ClearRequest()
	return _u
}

// Where appends a list predicates to the DiffUpdate builder.
func (_u *DiffUpdateOne) Where(ps ...predicate.Diff) *DiffUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiffUpdateOne) Select(field string, fields ...string) *DiffUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Diff entity.
func (_u *DiffUpdateOne) Save(ctx context.Context) (*Diff, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiffUpdateOne) SaveX(ctx context.Context) *Diff {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiffUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiffUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiffUpdateOne) check() error {
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Diff.request"`)
	}
	return nil
}

func (_u *DiffUpdateOne) sqlSave(ctx context.Context) (_node *Diff, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diff.Table, diff.Columns, sqlgraph.NewFieldSpec(diff.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Diff.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, diff.FieldID)
		for _, f := range fields {
			if !diff.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != diff.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FromResponseID(); ok {
		_spec.SetField(diff.FieldFromResponseID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ToResponseID(); ok {
		_spec.SetField(diff.FieldToResponseID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(diff.FieldContent, field.TypeString, value)
	}
	if _u.mutation.RequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   diff.RequestTable,
			Columns: []string{diff.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   diff.RequestTable,
			Columns: []string{diff.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Diff{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diff.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
