// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	entdiff "github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/predicate"
	"github.com/pedrobarco/mroki/ent/request"
	"github.com/pedrobarco/mroki/ent/response"
)

// DiffQuery is the builder for querying Diff entities.
type DiffQuery struct {
	config
	ctx              *QueryContext
	order            []entdiff.OrderOption
	inters           []Interceptor
	predicates       []predicate.Diff
	withRequest      *RequestQuery
	withFromResponse *ResponseQuery
	withToResponse   *ResponseQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DiffQuery builder.
func (_q *DiffQuery) Where(ps ...predicate.Diff) *DiffQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DiffQuery) Limit(limit int) *DiffQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DiffQuery) Offset(offset int) *DiffQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DiffQuery) Unique(unique bool) *DiffQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DiffQuery) Order(o ...entdiff.OrderOption) *DiffQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRequest chains the current query on the "request" edge.
func (_q *DiffQuery) QueryRequest() *RequestQuery {
	query := (&RequestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entdiff.Table, entdiff.FieldID, selector),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, entdiff.RequestTable, entdiff.RequestColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFromResponse chains the current query on the "from_response" edge.
func (_q *DiffQuery) QueryFromResponse() *ResponseQuery {
	query := (&ResponseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entdiff.Table, entdiff.FieldID, selector),
			sqlgraph.To(response.Table, response.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entdiff.FromResponseTable, entdiff.FromResponseColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryToResponse chains the current query on the "to_response" edge.
func (_q *DiffQuery) QueryToResponse() *ResponseQuery {
	query := (&ResponseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entdiff.Table, entdiff.FieldID, selector),
			sqlgraph.To(response.Table, response.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entdiff.ToResponseTable, entdiff.ToResponseColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Diff entity from the query.
// Returns a *NotFoundError when no Diff was found.
func (_q *DiffQuery) First(ctx context.Context) (*Diff, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entdiff.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DiffQuery) FirstX(ctx context.Context) *Diff {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Diff ID from the query.
// Returns a *NotFoundError when no Diff ID was found.
func (_q *DiffQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entdiff.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DiffQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Diff entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Diff entity is found.
// Returns a *NotFoundError when no Diff entities are found.
func (_q *DiffQuery) Only(ctx context.Context) (*Diff, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entdiff.Label}
	default:
		return nil, &NotSingularError{entdiff.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DiffQuery) OnlyX(ctx context.Context) *Diff {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Diff ID in the query.
// Returns a *NotSingularError when more than one Diff ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DiffQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entdiff.Label}
	default:
		err = &NotSingularError{entdiff.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DiffQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Diffs.
func (_q *DiffQuery) All(ctx context.Context) ([]*Diff, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Diff, *DiffQuery]()
	return withInterceptors[[]*Diff](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DiffQuery) AllX(ctx context.Context) []*Diff {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Diff IDs.
func (_q *DiffQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(entdiff.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DiffQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DiffQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DiffQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DiffQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DiffQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DiffQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DiffQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DiffQuery) Clone() *DiffQuery {
	if _q == nil {
		return nil
	}
	return &DiffQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]entdiff.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Diff{}, _q.predicates...),
		withRequest:      _q.withRequest.Clone(),
		withFromResponse: _q.withFromResponse.Clone(),
		withToResponse:   _q.withToResponse.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRequest tells the query-builder to eager-load the nodes that are connected to
// the "request" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DiffQuery) WithRequest(opts ...func(*RequestQuery)) *DiffQuery {
	query := (&RequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRequest = query
	return _q
}

// WithFromResponse tells the query-builder to eager-load the nodes that are connected to
// the "from_response" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DiffQuery) WithFromResponse(opts ...func(*ResponseQuery)) *DiffQuery {
	query := (&ResponseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFromResponse = query
	return _q
}

// WithToResponse tells the query-builder to eager-load the nodes that are connected to
// the "to_response" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DiffQuery) WithToResponse(opts ...func(*ResponseQuery)) *DiffQuery {
	query := (&ResponseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withToResponse = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequestID uuid.UUID `json:"request_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Diff.Query().
//		GroupBy(entdiff.FieldRequestID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DiffQuery) GroupBy(field string, fields ...string) *DiffGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DiffGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = entdiff.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequestID uuid.UUID `json:"request_id,omitempty"`
//	}
//
//	client.Diff.Query().
//		Select(entdiff.FieldRequestID).
//		Scan(ctx, &v)
func (_q *DiffQuery) Select(fields ...string) *DiffSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DiffSelect{DiffQuery: _q}
	sbuild.label = entdiff.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DiffSelect configured with the given aggregations.
func (_q *DiffQuery) Aggregate(fns ...AggregateFunc) *DiffSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DiffQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !entdiff.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DiffQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Diff, error) {
	var (
		nodes       = []*Diff{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withRequest != nil,
			_q.withFromResponse != nil,
			_q.withToResponse != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Diff).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Diff{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRequest; query != nil {
		if err := _q.loadRequest(ctx, query, nodes, nil,
			func(n *Diff, e *Request) { n.Edges.Request = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFromResponse; query != nil {
		if err := _q.loadFromResponse(ctx, query, nodes, nil,
			func(n *Diff, e *Response) { n.Edges.FromResponse = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withToResponse; query != nil {
		if err := _q.loadToResponse(ctx, query, nodes, nil,
			func(n *Diff, e *Response) { n.Edges.ToResponse = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DiffQuery) loadRequest(ctx context.Context, query *RequestQuery, nodes []*Diff, init func(*Diff), assign func(*Diff, *Request)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Diff)
	for i := range nodes {
		fk := nodes[i].RequestID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(request.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "request_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DiffQuery) loadFromResponse(ctx context.Context, query *ResponseQuery, nodes []*Diff, init func(*Diff), assign func(*Diff, *Response)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Diff)
	for i := range nodes {
		fk := nodes[i].FromResponseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(response.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "from_response_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DiffQuery) loadToResponse(ctx context.Context, query *ResponseQuery, nodes []*Diff, init func(*Diff), assign func(*Diff, *Response)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Diff)
	for i := range nodes {
		fk := nodes[i].ToResponseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(response.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "to_response_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DiffQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DiffQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(entdiff.Table, entdiff.Columns, sqlgraph.NewFieldSpec(entdiff.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entdiff.FieldID)
		for i := range fields {
			if fields[i] != entdiff.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRequest != nil {
			_spec.Node.AddColumnOnce(entdiff.FieldRequestID)
		}
		if _q.withFromResponse != nil {
			_spec.Node.AddColumnOnce(entdiff.FieldFromResponseID)
		}
		if _q.withToResponse != nil {
			_spec.Node.AddColumnOnce(entdiff.FieldToResponseID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DiffQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(entdiff.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = entdiff.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DiffGroupBy is the group-by builder for Diff entities.
type DiffGroupBy struct {
	selector
	build *DiffQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DiffGroupBy) Aggregate(fns ...AggregateFunc) *DiffGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DiffGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiffQuery, *DiffGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DiffGroupBy) sqlScan(ctx context.Context, root *DiffQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DiffSelect is the builder for selecting fields of Diff entities.
type DiffSelect struct {
	*DiffQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DiffSelect) Aggregate(fns ...AggregateFunc) *DiffSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DiffSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiffQuery, *DiffSelect](ctx, _s.DiffQuery, _s, _s.inters, v)
}

func (_s *DiffSelect) sqlScan(ctx context.Context, root *DiffQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
