// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/gate"
)

// Gate is the model entity for the Gate schema.
type Gate struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// LiveURL holds the value of the "live_url" field.
	LiveURL string `json:"live_url,omitempty"`
	// ShadowURL holds the value of the "shadow_url" field.
	ShadowURL string `json:"shadow_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// DiffIgnoredFields holds the value of the "diff_ignored_fields" field.
	DiffIgnoredFields []string `json:"diff_ignored_fields,omitempty"`
	// DiffIncludedFields holds the value of the "diff_included_fields" field.
	DiffIncludedFields []string `json:"diff_included_fields,omitempty"`
	// DiffFloatTolerance holds the value of the "diff_float_tolerance" field.
	DiffFloatTolerance float64 `json:"diff_float_tolerance,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GateQuery when eager-loading is set.
	Edges        GateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GateEdges holds the relations/edges for other nodes in the graph.
type GateEdges struct {
	// Requests holds the value of the requests edge.
	Requests []*Request `json:"requests,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RequestsOrErr returns the Requests value or an error if the edge
// was not loaded in eager-loading.
func (e GateEdges) RequestsOrErr() ([]*Request, error) {
	if e.loadedTypes[0] {
		return e.Requests, nil
	}
	return nil, &NotLoadedError{edge: "requests"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Gate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gate.FieldDiffIgnoredFields, gate.FieldDiffIncludedFields:
			values[i] = new([]byte)
		case gate.FieldDiffFloatTolerance:
			values[i] = new(sql.NullFloat64)
		case gate.FieldName, gate.FieldLiveURL, gate.FieldShadowURL:
			values[i] = new(sql.NullString)
		case gate.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case gate.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Gate fields.
func (_m *Gate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case gate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case gate.FieldLiveURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field live_url", values[i])
			} else if value.Valid {
				_m.LiveURL = value.String
			}
		case gate.FieldShadowURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shadow_url", values[i])
			} else if value.Valid {
				_m.ShadowURL = value.String
			}
		case gate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gate.FieldDiffIgnoredFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field diff_ignored_fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DiffIgnoredFields); err != nil {
					return fmt.Errorf("unmarshal field diff_ignored_fields: %w", err)
				}
			}
		case gate.FieldDiffIncludedFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field diff_included_fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DiffIncludedFields); err != nil {
					return fmt.Errorf("unmarshal field diff_included_fields: %w", err)
				}
			}
		case gate.FieldDiffFloatTolerance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field diff_float_tolerance", values[i])
			} else if value.Valid {
				_m.DiffFloatTolerance = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Gate.
// This includes values selected through modifiers, order, etc.
func (_m *Gate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequests queries the "requests" edge of the Gate entity.
func (_m *Gate) QueryRequests() *RequestQuery {
	return NewGateClient(_m.config).QueryRequests(_m)
}

// Update returns a builder for updating this Gate.
// Note that you need to call Gate.Unwrap() before calling this method if this Gate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Gate) Update() *GateUpdateOne {
	return NewGateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Gate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Gate) Unwrap() *Gate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Gate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Gate) String() string {
	var builder strings.Builder
	builder.WriteString("Gate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("live_url=")
	builder.WriteString(_m.LiveURL)
	builder.WriteString(", ")
	builder.WriteString("shadow_url=")
	builder.WriteString(_m.ShadowURL)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("diff_ignored_fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiffIgnoredFields))
	builder.WriteString(", ")
	builder.WriteString("diff_included_fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiffIncludedFields))
	builder.WriteString(", ")
	builder.WriteString("diff_float_tolerance=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiffFloatTolerance))
	builder.WriteByte(')')
	return builder.String()
}

// Gates is a parsable slice of Gate.
type Gates []*Gate
