// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/gate"
	"github.com/pedrobarco/mroki/ent/request"
)

// GateCreate is the builder for creating a Gate entity.
type GateCreate struct {
	config
	mutation *GateMutation
	hooks    []Hook
}

// SetLiveURL sets the "live_url" field.
func (_c *GateCreate) SetLiveURL(v string) *GateCreate {
	_c.mutation.SetLiveURL(v)
	return _c
}

// SetShadowURL sets the "shadow_url" field.
func (_c *GateCreate) SetShadowURL(v string) *GateCreate {
	_c.mutation.SetShadowURL(v)
	return _c
}

// SetID sets the "id" field.
func (_c *GateCreate) SetID(v uuid.UUID) *GateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GateCreate) SetNillableID(v *uuid.UUID) *GateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (_c *GateCreate) AddRequestIDs(ids ...uuid.UUID) *GateCreate {
	_c.mutation.AddRequestIDs(ids...)
	return _c
}

// AddRequests adds the "requests" edges to the Request entity.
func (_c *GateCreate) AddRequests(v ...*Request) *GateCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRequestIDs(ids...)
}

// Mutation returns the GateMutation object of the builder.
func (_c *GateCreate) Mutation() *GateMutation {
	return _c.mutation
}

// Save creates the Gate in the database.
func (_c *GateCreate) Save(ctx context.Context) (*Gate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GateCreate) SaveX(ctx context.Context) *Gate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GateCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := gate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GateCreate) check() error {
	if _, ok := _c.mutation.LiveURL(); !ok {
		return &ValidationError{Name: "live_url", err: errors.New(`ent: missing required field "Gate.live_url"`)}
	}
	if v, ok := _c.mutation.LiveURL(); ok {
		if err := gate.LiveURLValidator(v); err != nil {
			return &ValidationError{Name: "live_url", err: fmt.Errorf(`ent: validator failed for field "Gate.live_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ShadowURL(); !ok {
		return &ValidationError{Name: "shadow_url", err: errors.New(`ent: missing required field "Gate.shadow_url"`)}
	}
	if v, ok := _c.mutation.ShadowURL(); ok {
		if err := gate.ShadowURLValidator(v); err != nil {
			return &ValidationError{Name: "shadow_url", err: fmt.Errorf(`ent: validator failed for field "Gate.shadow_url": %w`, err)}
		}
	}
	return nil
}

func (_c *GateCreate) sqlSave(ctx context.Context) (*Gate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GateCreate) createSpec() (*Gate, *sqlgraph.CreateSpec) {
	var (
		_node = &Gate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gate.Table, sqlgraph.NewFieldSpec(gate.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.LiveURL(); ok {
		_spec.SetField(gate.FieldLiveURL, field.TypeString, value)
		_node.LiveURL = value
	}
	if value, ok := _c.mutation.ShadowURL(); ok {
		_spec.SetField(gate.FieldShadowURL, field.TypeString, value)
		_node.ShadowURL = value
	}
	if nodes := _c.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.RequestsTable,
			Columns: []string{gate.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GateCreateBulk is the builder for creating many Gate entities in bulk.
type GateCreateBulk struct {
	config
	err      error
	builders []*GateCreate
}

// Save creates the Gate entities in the database.
func (_c *GateCreateBulk) Save(ctx context.Context) ([]*Gate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Gate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GateCreateBulk) SaveX(ctx context.Context) []*Gate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
