// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/gate"
	"github.com/pedrobarco/mroki/ent/predicate"
	"github.com/pedrobarco/mroki/ent/request"
)

// GateUpdate is the builder for updating Gate entities.
type GateUpdate struct {
	config
	hooks    []Hook
	mutation *GateMutation
}

// Where appends a list predicates to the GateUpdate builder.
func (_u *GateUpdate) Where(ps ...predicate.Gate) *GateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLiveURL sets the "live_url" field.
func (_u *GateUpdate) SetLiveURL(v string) *GateUpdate {
	_u.mutation.SetLiveURL(v)
	return _u
}

// SetNillableLiveURL sets the "live_url" field if the given value is not nil.
func (_u *GateUpdate) SetNillableLiveURL(v *string) *GateUpdate {
	if v != nil {
		_u.SetLiveURL(*v)
	}
	return _u
}

// SetShadowURL sets the "shadow_url" field.
func (_u *GateUpdate) SetShadowURL(v string) *GateUpdate {
	_u.mutation.SetShadowURL(v)
	return _u
}

// SetNillableShadowURL sets the "shadow_url" field if the given value is not nil.
func (_u *GateUpdate) SetNillableShadowURL(v *string) *GateUpdate {
	if v != nil {
		_u.SetShadowURL(*v)
	}
	return _u
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (_u *GateUpdate) AddRequestIDs(ids ...uuid.UUID) *GateUpdate {
	_u.mutation.AddRequestIDs(ids...)
	return _u
}

// AddRequests adds the "requests" edges to the Request entity.
func (_u *GateUpdate) AddRequests(v ...*Request) *GateUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestIDs(ids...)
}

// Mutation returns the GateMutation object of the builder.
func (_u *GateUpdate) Mutation() *GateMutation {
	return _u.mutation
}

// ClearRequests clears all "requests" edges to the Request entity.
func (_u *GateUpdate) ClearRequests() *GateUpdate {
	_u.mutation.ClearRequests()
	return _u
}

// RemoveRequestIDs removes the "requests" edge to Request entities by IDs.
func (_u *GateUpdate) RemoveRequestIDs(ids ...uuid.UUID) *GateUpdate {
	_u.mutation.RemoveRequestIDs(ids...)
	return _u
}

// RemoveRequests removes "requests" edges to Request entities.
func (_u *GateUpdate) RemoveRequests(v ...*Request) *GateUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GateUpdate) check() error {
	if v, ok := _u.mutation.LiveURL(); ok {
		if err := gate.LiveURLValidator(v); err != nil {
			return &ValidationError{Name: "live_url", err: fmt.Errorf(`ent: validator failed for field "Gate.live_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ShadowURL(); ok {
		if err := gate.ShadowURLValidator(v); err != nil {
			return &ValidationError{Name: "shadow_url", err: fmt.Errorf(`ent: validator failed for field "Gate.shadow_url": %w`, err)}
		}
	}
	return nil
}

func (_u *GateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gate.Table, gate.Columns, sqlgraph.NewFieldSpec(gate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LiveURL(); ok {
		_spec.SetField(gate.FieldLiveURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShadowURL(); ok {
		_spec.SetField(gate.FieldShadowURL, field.TypeString, value)
	}
	if _u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.RequestsTable,
			Columns: []string{gate.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.RequestsTable,
			Columns: []string{gate.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.RequestsTable,
			Columns: []string{gate.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GateUpdateOne is the builder for updating a single Gate entity.
type GateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GateMutation
}

// SetLiveURL sets the "live_url" field.
func (_u *GateUpdateOne) SetLiveURL(v string) *GateUpdateOne {
	_u.mutation.SetLiveURL(v)
	return _u
}

// SetNillableLiveURL sets the "live_url" field if the given value is not nil.
func (_u *GateUpdateOne) SetNillableLiveURL(v *string) *GateUpdateOne {
	if v != nil {
		_u.SetLiveURL(*v)
	}
	return _u
}

// SetShadowURL sets the "shadow_url" field.
func (_u *GateUpdateOne) SetShadowURL(v string) *GateUpdateOne {
	_u.mutation.SetShadowURL(v)
	return _u
}

// SetNillableShadowURL sets the "shadow_url" field if the given value is not nil.
func (_u *GateUpdateOne) SetNillableShadowURL(v *string) *GateUpdateOne {
	if v != nil {
		_u.SetShadowURL(*v)
	}
	return _u
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (_u *GateUpdateOne) AddRequestIDs(ids ...uuid.UUID) *GateUpdateOne {
	_u.mutation.AddRequestIDs(ids...)
	return _u
}

// AddRequests adds the "requests" edges to the Request entity.
func (_u *GateUpdateOne) AddRequests(v ...*Request) *GateUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestIDs(ids...)
}

// Mutation returns the GateMutation object of the builder.
func (_u *GateUpdateOne) Mutation() *GateMutation {
	return _u.mutation
}

// ClearRequests clears all "requests" edges to the Request entity.
func (_u *GateUpdateOne) ClearRequests() *GateUpdateOne {
	_u.mutation.ClearRequests()
	return _u
}

// RemoveRequestIDs removes the "requests" edge to Request entities by IDs.
func (_u *GateUpdateOne) RemoveRequestIDs(ids ...uuid.UUID) *GateUpdateOne {
	_u.mutation.RemoveRequestIDs(ids...)
	return _u
}

// RemoveRequests removes "requests" edges to Request entities.
func (_u *GateUpdateOne) RemoveRequests(v ...*Request) *GateUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestIDs(ids...)
}

// Where appends a list predicates to the GateUpdate builder.
func (_u *GateUpdateOne) Where(ps ...predicate.Gate) *GateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GateUpdateOne) Select(field string, fields ...string) *GateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Gate entity.
func (_u *GateUpdateOne) Save(ctx context.Context) (*Gate, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GateUpdateOne) SaveX(ctx context.Context) *Gate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GateUpdateOne) check() error {
	if v, ok := _u.mutation.LiveURL(); ok {
		if err := gate.LiveURLValidator(v); err != nil {
			return &ValidationError{Name: "live_url", err: fmt.Errorf(`ent: validator failed for field "Gate.live_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ShadowURL(); ok {
		if err := gate.ShadowURLValidator(v); err != nil {
			return &ValidationError{Name: "shadow_url", err: fmt.Errorf(`ent: validator failed for field "Gate.shadow_url": %w`, err)}
		}
	}
	return nil
}

func (_u *GateUpdateOne) sqlSave(ctx context.Context) (_node *Gate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gate.Table, gate.Columns, sqlgraph.NewFieldSpec(gate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Gate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gate.FieldID)
		for _, f := range fields {
			if !gate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LiveURL(); ok {
		_spec.SetField(gate.FieldLiveURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShadowURL(); ok {
		_spec.SetField(gate.FieldShadowURL, field.TypeString, value)
	}
	if _u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.RequestsTable,
			Columns: []string{gate.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.RequestsTable,
			Columns: []string{gate.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   gate.RequestsTable,
			Columns: []string{gate.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Gate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
