// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	entdiff "github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/gate"
	"github.com/pedrobarco/mroki/ent/predicate"
	"github.com/pedrobarco/mroki/ent/request"
	"github.com/pedrobarco/mroki/ent/response"
	"github.com/pedrobarco/mroki/pkg/diff"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDiff     = "Diff"
	TypeGate     = "Gate"
	TypeRequest  = "Request"
	TypeResponse = "Response"
)

// DiffMutation represents an operation that mutates the Diff nodes in the graph.
type DiffMutation struct {
	config
	op                   Op
	typ                  string
	id                   *uuid.UUID
	content              *[]diff.PatchOp
	appendcontent        []diff.PatchOp
	created_at           *time.Time
	clearedFields        map[string]struct{}
	request              *uuid.UUID
	clearedrequest       bool
	from_response        *uuid.UUID
	clearedfrom_response bool
	to_response          *uuid.UUID
	clearedto_response   bool
	done                 bool
	oldValue             func(context.Context) (*Diff, error)
	predicates           []predicate.Diff
}

var _ ent.Mutation = (*DiffMutation)(nil)

// diffOption allows management of the mutation configuration using functional options.
type diffOption func(*DiffMutation)

// newDiffMutation creates new mutation for the Diff entity.
func newDiffMutation(c config, op Op, opts ...diffOption) *DiffMutation {
	m := &DiffMutation{
		config:        c,
		op:            op,
		typ:           TypeDiff,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDiffID sets the ID field of the mutation.
func withDiffID(id uuid.UUID) diffOption {
	return func(m *DiffMutation) {
		var (
			err   error
			once  sync.Once
			value *Diff
		)
		m.oldValue = func(ctx context.Context) (*Diff, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Diff.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDiff sets the old Diff of the mutation.
func withDiff(node *Diff) diffOption {
	return func(m *DiffMutation) {
		m.oldValue = func(context.Context) (*Diff, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DiffMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DiffMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Diff entities.
func (m *DiffMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DiffMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DiffMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Diff.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetRequestID sets the "request_id" field.
func (m *DiffMutation) SetRequestID(u uuid.UUID) {
	m.request = &u
}

// RequestID returns the value of the "request_id" field in the mutation.
func (m *DiffMutation) RequestID() (r uuid.UUID, exists bool) {
	v := m.request
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestID returns the old "request_id" field's value of the Diff entity.
// If the Diff object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiffMutation) OldRequestID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestID: %w", err)
	}
	return oldValue.RequestID, nil
}

// ResetRequestID resets all changes to the "request_id" field.
func (m *DiffMutation) ResetRequestID() {
	m.request = nil
}

// SetFromResponseID sets the "from_response_id" field.
func (m *DiffMutation) SetFromResponseID(u uuid.UUID) {
	m.from_response = &u
}

// FromResponseID returns the value of the "from_response_id" field in the mutation.
func (m *DiffMutation) FromResponseID() (r uuid.UUID, exists bool) {
	v := m.from_response
	if v == nil {
		return
	}
	return *v, true
}

// OldFromResponseID returns the old "from_response_id" field's value of the Diff entity.
// If the Diff object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiffMutation) OldFromResponseID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFromResponseID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFromResponseID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFromResponseID: %w", err)
	}
	return oldValue.FromResponseID, nil
}

// ResetFromResponseID resets all changes to the "from_response_id" field.
func (m *DiffMutation) ResetFromResponseID() {
	m.from_response = nil
}

// SetToResponseID sets the "to_response_id" field.
func (m *DiffMutation) SetToResponseID(u uuid.UUID) {
	m.to_response = &u
}

// ToResponseID returns the value of the "to_response_id" field in the mutation.
func (m *DiffMutation) ToResponseID() (r uuid.UUID, exists bool) {
	v := m.to_response
	if v == nil {
		return
	}
	return *v, true
}

// OldToResponseID returns the old "to_response_id" field's value of the Diff entity.
// If the Diff object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiffMutation) OldToResponseID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldToResponseID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldToResponseID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldToResponseID: %w", err)
	}
	return oldValue.ToResponseID, nil
}

// ResetToResponseID resets all changes to the "to_response_id" field.
func (m *DiffMutation) ResetToResponseID() {
	m.to_response = nil
}

// SetContent sets the "content" field.
func (m *DiffMutation) SetContent(do []diff.PatchOp) {
	m.content = &do
	m.appendcontent = nil
}

// Content returns the value of the "content" field in the mutation.
func (m *DiffMutation) Content() (r []diff.PatchOp, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the Diff entity.
// If the Diff object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiffMutation) OldContent(ctx context.Context) (v []diff.PatchOp, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// AppendContent adds do to the "content" field.
func (m *DiffMutation) AppendContent(do []diff.PatchOp) {
	m.appendcontent = append(m.appendcontent, do...)
}

// AppendedContent returns the list of values that were appended to the "content" field in this mutation.
func (m *DiffMutation) AppendedContent() ([]diff.PatchOp, bool) {
	if len(m.appendcontent) == 0 {
		return nil, false
	}
	return m.appendcontent, true
}

// ResetContent resets all changes to the "content" field.
func (m *DiffMutation) ResetContent() {
	m.content = nil
	m.appendcontent = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *DiffMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DiffMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Diff entity.
// If the Diff object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DiffMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DiffMutation) ResetCreatedAt() {
	m.created_at = nil
}

// ClearRequest clears the "request" edge to the Request entity.
func (m *DiffMutation) ClearRequest() {
	m.clearedrequest = true
	m.clearedFields[entdiff.FieldRequestID] = struct{}{}
}

// RequestCleared reports if the "request" edge to the Request entity was cleared.
func (m *DiffMutation) RequestCleared() bool {
	return m.clearedrequest
}

// RequestIDs returns the "request" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// RequestID instead. It exists only for internal usage by the builders.
func (m *DiffMutation) RequestIDs() (ids []uuid.UUID) {
	if id := m.request; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetRequest resets all changes to the "request" edge.
func (m *DiffMutation) ResetRequest() {
	m.request = nil
	m.clearedrequest = false
}

// ClearFromResponse clears the "from_response" edge to the Response entity.
func (m *DiffMutation) ClearFromResponse() {
	m.clearedfrom_response = true
	m.clearedFields[entdiff.FieldFromResponseID] = struct{}{}
}

// FromResponseCleared reports if the "from_response" edge to the Response entity was cleared.
func (m *DiffMutation) FromResponseCleared() bool {
	return m.clearedfrom_response
}

// FromResponseIDs returns the "from_response" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// FromResponseID instead. It exists only for internal usage by the builders.
func (m *DiffMutation) FromResponseIDs() (ids []uuid.UUID) {
	if id := m.from_response; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetFromResponse resets all changes to the "from_response" edge.
func (m *DiffMutation) ResetFromResponse() {
	m.from_response = nil
	m.clearedfrom_response = false
}

// ClearToResponse clears the "to_response" edge to the Response entity.
func (m *DiffMutation) ClearToResponse() {
	m.clearedto_response = true
	m.clearedFields[entdiff.FieldToResponseID] = struct{}{}
}

// ToResponseCleared reports if the "to_response" edge to the Response entity was cleared.
func (m *DiffMutation) ToResponseCleared() bool {
	return m.clearedto_response
}

// ToResponseIDs returns the "to_response" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ToResponseID instead. It exists only for internal usage by the builders.
func (m *DiffMutation) ToResponseIDs() (ids []uuid.UUID) {
	if id := m.to_response; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetToResponse resets all changes to the "to_response" edge.
func (m *DiffMutation) ResetToResponse() {
	m.to_response = nil
	m.clearedto_response = false
}

// Where appends a list predicates to the DiffMutation builder.
func (m *DiffMutation) Where(ps ...predicate.Diff) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DiffMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DiffMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Diff, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DiffMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DiffMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Diff).
func (m *DiffMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DiffMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.request != nil {
		fields = append(fields, entdiff.FieldRequestID)
	}
	if m.from_response != nil {
		fields = append(fields, entdiff.FieldFromResponseID)
	}
	if m.to_response != nil {
		fields = append(fields, entdiff.FieldToResponseID)
	}
	if m.content != nil {
		fields = append(fields, entdiff.FieldContent)
	}
	if m.created_at != nil {
		fields = append(fields, entdiff.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DiffMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case entdiff.FieldRequestID:
		return m.RequestID()
	case entdiff.FieldFromResponseID:
		return m.FromResponseID()
	case entdiff.FieldToResponseID:
		return m.ToResponseID()
	case entdiff.FieldContent:
		return m.Content()
	case entdiff.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DiffMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case entdiff.FieldRequestID:
		return m.OldRequestID(ctx)
	case entdiff.FieldFromResponseID:
		return m.OldFromResponseID(ctx)
	case entdiff.FieldToResponseID:
		return m.OldToResponseID(ctx)
	case entdiff.FieldContent:
		return m.OldContent(ctx)
	case entdiff.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Diff field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DiffMutation) SetField(name string, value ent.Value) error {
	switch name {
	case entdiff.FieldRequestID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestID(v)
		return nil
	case entdiff.FieldFromResponseID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFromResponseID(v)
		return nil
	case entdiff.FieldToResponseID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetToResponseID(v)
		return nil
	case entdiff.FieldContent:
		v, ok := value.([]diff.PatchOp)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case entdiff.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Diff field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DiffMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DiffMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DiffMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Diff numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DiffMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DiffMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DiffMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Diff nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DiffMutation) ResetField(name string) error {
	switch name {
	case entdiff.FieldRequestID:
		m.ResetRequestID()
		return nil
	case entdiff.FieldFromResponseID:
		m.ResetFromResponseID()
		return nil
	case entdiff.FieldToResponseID:
		m.ResetToResponseID()
		return nil
	case entdiff.FieldContent:
		m.ResetContent()
		return nil
	case entdiff.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Diff field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DiffMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.request != nil {
		edges = append(edges, entdiff.EdgeRequest)
	}
	if m.from_response != nil {
		edges = append(edges, entdiff.EdgeFromResponse)
	}
	if m.to_response != nil {
		edges = append(edges, entdiff.EdgeToResponse)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DiffMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case entdiff.EdgeRequest:
		if id := m.request; id != nil {
			return []ent.Value{*id}
		}
	case entdiff.EdgeFromResponse:
		if id := m.from_response; id != nil {
			return []ent.Value{*id}
		}
	case entdiff.EdgeToResponse:
		if id := m.to_response; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DiffMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DiffMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DiffMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedrequest {
		edges = append(edges, entdiff.EdgeRequest)
	}
	if m.clearedfrom_response {
		edges = append(edges, entdiff.EdgeFromResponse)
	}
	if m.clearedto_response {
		edges = append(edges, entdiff.EdgeToResponse)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DiffMutation) EdgeCleared(name string) bool {
	switch name {
	case entdiff.EdgeRequest:
		return m.clearedrequest
	case entdiff.EdgeFromResponse:
		return m.clearedfrom_response
	case entdiff.EdgeToResponse:
		return m.clearedto_response
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DiffMutation) ClearEdge(name string) error {
	switch name {
	case entdiff.EdgeRequest:
		m.ClearRequest()
		return nil
	case entdiff.EdgeFromResponse:
		m.ClearFromResponse()
		return nil
	case entdiff.EdgeToResponse:
		m.ClearToResponse()
		return nil
	}
	return fmt.Errorf("unknown Diff unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DiffMutation) ResetEdge(name string) error {
	switch name {
	case entdiff.EdgeRequest:
		m.ResetRequest()
		return nil
	case entdiff.EdgeFromResponse:
		m.ResetFromResponse()
		return nil
	case entdiff.EdgeToResponse:
		m.ResetToResponse()
		return nil
	}
	return fmt.Errorf("unknown Diff edge %s", name)
}

// GateMutation represents an operation that mutates the Gate nodes in the graph.
type GateMutation struct {
	config
	op              Op
	typ             string
	id              *uuid.UUID
	name            *string
	live_url        *string
	shadow_url      *string
	created_at      *time.Time
	clearedFields   map[string]struct{}
	requests        map[uuid.UUID]struct{}
	removedrequests map[uuid.UUID]struct{}
	clearedrequests bool
	done            bool
	oldValue        func(context.Context) (*Gate, error)
	predicates      []predicate.Gate
}

var _ ent.Mutation = (*GateMutation)(nil)

// gateOption allows management of the mutation configuration using functional options.
type gateOption func(*GateMutation)

// newGateMutation creates new mutation for the Gate entity.
func newGateMutation(c config, op Op, opts ...gateOption) *GateMutation {
	m := &GateMutation{
		config:        c,
		op:            op,
		typ:           TypeGate,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withGateID sets the ID field of the mutation.
func withGateID(id uuid.UUID) gateOption {
	return func(m *GateMutation) {
		var (
			err   error
			once  sync.Once
			value *Gate
		)
		m.oldValue = func(ctx context.Context) (*Gate, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Gate.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withGate sets the old Gate of the mutation.
func withGate(node *Gate) gateOption {
	return func(m *GateMutation) {
		m.oldValue = func(context.Context) (*Gate, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m GateMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m GateMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Gate entities.
func (m *GateMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *GateMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *GateMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Gate.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *GateMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *GateMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Gate entity.
// If the Gate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GateMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *GateMutation) ResetName() {
	m.name = nil
}

// SetLiveURL sets the "live_url" field.
func (m *GateMutation) SetLiveURL(s string) {
	m.live_url = &s
}

// LiveURL returns the value of the "live_url" field in the mutation.
func (m *GateMutation) LiveURL() (r string, exists bool) {
	v := m.live_url
	if v == nil {
		return
	}
	return *v, true
}

// OldLiveURL returns the old "live_url" field's value of the Gate entity.
// If the Gate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GateMutation) OldLiveURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLiveURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLiveURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLiveURL: %w", err)
	}
	return oldValue.LiveURL, nil
}

// ResetLiveURL resets all changes to the "live_url" field.
func (m *GateMutation) ResetLiveURL() {
	m.live_url = nil
}

// SetShadowURL sets the "shadow_url" field.
func (m *GateMutation) SetShadowURL(s string) {
	m.shadow_url = &s
}

// ShadowURL returns the value of the "shadow_url" field in the mutation.
func (m *GateMutation) ShadowURL() (r string, exists bool) {
	v := m.shadow_url
	if v == nil {
		return
	}
	return *v, true
}

// OldShadowURL returns the old "shadow_url" field's value of the Gate entity.
// If the Gate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GateMutation) OldShadowURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldShadowURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldShadowURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldShadowURL: %w", err)
	}
	return oldValue.ShadowURL, nil
}

// ResetShadowURL resets all changes to the "shadow_url" field.
func (m *GateMutation) ResetShadowURL() {
	m.shadow_url = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *GateMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *GateMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Gate entity.
// If the Gate object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GateMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *GateMutation) ResetCreatedAt() {
	m.created_at = nil
}

// AddRequestIDs adds the "requests" edge to the Request entity by ids.
func (m *GateMutation) AddRequestIDs(ids ...uuid.UUID) {
	if m.requests == nil {
		m.requests = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.requests[ids[i]] = struct{}{}
	}
}

// ClearRequests clears the "requests" edge to the Request entity.
func (m *GateMutation) ClearRequests() {
	m.clearedrequests = true
}

// RequestsCleared reports if the "requests" edge to the Request entity was cleared.
func (m *GateMutation) RequestsCleared() bool {
	return m.clearedrequests
}

// RemoveRequestIDs removes the "requests" edge to the Request entity by IDs.
func (m *GateMutation) RemoveRequestIDs(ids ...uuid.UUID) {
	if m.removedrequests == nil {
		m.removedrequests = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.requests, ids[i])
		m.removedrequests[ids[i]] = struct{}{}
	}
}

// RemovedRequests returns the removed IDs of the "requests" edge to the Request entity.
func (m *GateMutation) RemovedRequestsIDs() (ids []uuid.UUID) {
	for id := range m.removedrequests {
		ids = append(ids, id)
	}
	return
}

// RequestsIDs returns the "requests" edge IDs in the mutation.
func (m *GateMutation) RequestsIDs() (ids []uuid.UUID) {
	for id := range m.requests {
		ids = append(ids, id)
	}
	return
}

// ResetRequests resets all changes to the "requests" edge.
func (m *GateMutation) ResetRequests() {
	m.requests = nil
	m.clearedrequests = false
	m.removedrequests = nil
}

// Where appends a list predicates to the GateMutation builder.
func (m *GateMutation) Where(ps ...predicate.Gate) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the GateMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *GateMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Gate, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *GateMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *GateMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Gate).
func (m *GateMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *GateMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, gate.FieldName)
	}
	if m.live_url != nil {
		fields = append(fields, gate.FieldLiveURL)
	}
	if m.shadow_url != nil {
		fields = append(fields, gate.FieldShadowURL)
	}
	if m.created_at != nil {
		fields = append(fields, gate.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *GateMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case gate.FieldName:
		return m.Name()
	case gate.FieldLiveURL:
		return m.LiveURL()
	case gate.FieldShadowURL:
		return m.ShadowURL()
	case gate.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *GateMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case gate.FieldName:
		return m.OldName(ctx)
	case gate.FieldLiveURL:
		return m.OldLiveURL(ctx)
	case gate.FieldShadowURL:
		return m.OldShadowURL(ctx)
	case gate.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Gate field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GateMutation) SetField(name string, value ent.Value) error {
	switch name {
	case gate.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case gate.FieldLiveURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLiveURL(v)
		return nil
	case gate.FieldShadowURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetShadowURL(v)
		return nil
	case gate.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Gate field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *GateMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *GateMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GateMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Gate numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *GateMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *GateMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *GateMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Gate nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *GateMutation) ResetField(name string) error {
	switch name {
	case gate.FieldName:
		m.ResetName()
		return nil
	case gate.FieldLiveURL:
		m.ResetLiveURL()
		return nil
	case gate.FieldShadowURL:
		m.ResetShadowURL()
		return nil
	case gate.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Gate field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *GateMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.requests != nil {
		edges = append(edges, gate.EdgeRequests)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *GateMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case gate.EdgeRequests:
		ids := make([]ent.Value, 0, len(m.requests))
		for id := range m.requests {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *GateMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedrequests != nil {
		edges = append(edges, gate.EdgeRequests)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *GateMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case gate.EdgeRequests:
		ids := make([]ent.Value, 0, len(m.removedrequests))
		for id := range m.removedrequests {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *GateMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedrequests {
		edges = append(edges, gate.EdgeRequests)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *GateMutation) EdgeCleared(name string) bool {
	switch name {
	case gate.EdgeRequests:
		return m.clearedrequests
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *GateMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Gate unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *GateMutation) ResetEdge(name string) error {
	switch name {
	case gate.EdgeRequests:
		m.ResetRequests()
		return nil
	}
	return fmt.Errorf("unknown Gate edge %s", name)
}

// RequestMutation represents an operation that mutates the Request nodes in the graph.
type RequestMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	agent_id         *string
	method           *string
	_path            *string
	headers          *map[string][]string
	body             *[]byte
	created_at       *time.Time
	clearedFields    map[string]struct{}
	gate             *uuid.UUID
	clearedgate      bool
	responses        map[uuid.UUID]struct{}
	removedresponses map[uuid.UUID]struct{}
	clearedresponses bool
	diff             *uuid.UUID
	cleareddiff      bool
	done             bool
	oldValue         func(context.Context) (*Request, error)
	predicates       []predicate.Request
}

var _ ent.Mutation = (*RequestMutation)(nil)

// requestOption allows management of the mutation configuration using functional options.
type requestOption func(*RequestMutation)

// newRequestMutation creates new mutation for the Request entity.
func newRequestMutation(c config, op Op, opts ...requestOption) *RequestMutation {
	m := &RequestMutation{
		config:        c,
		op:            op,
		typ:           TypeRequest,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRequestID sets the ID field of the mutation.
func withRequestID(id uuid.UUID) requestOption {
	return func(m *RequestMutation) {
		var (
			err   error
			once  sync.Once
			value *Request
		)
		m.oldValue = func(ctx context.Context) (*Request, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Request.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRequest sets the old Request of the mutation.
func withRequest(node *Request) requestOption {
	return func(m *RequestMutation) {
		m.oldValue = func(context.Context) (*Request, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RequestMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RequestMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Request entities.
func (m *RequestMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RequestMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RequestMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Request.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetGateID sets the "gate_id" field.
func (m *RequestMutation) SetGateID(u uuid.UUID) {
	m.gate = &u
}

// GateID returns the value of the "gate_id" field in the mutation.
func (m *RequestMutation) GateID() (r uuid.UUID, exists bool) {
	v := m.gate
	if v == nil {
		return
	}
	return *v, true
}

// OldGateID returns the old "gate_id" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldGateID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGateID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGateID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGateID: %w", err)
	}
	return oldValue.GateID, nil
}

// ResetGateID resets all changes to the "gate_id" field.
func (m *RequestMutation) ResetGateID() {
	m.gate = nil
}

// SetAgentID sets the "agent_id" field.
func (m *RequestMutation) SetAgentID(s string) {
	m.agent_id = &s
}

// AgentID returns the value of the "agent_id" field in the mutation.
func (m *RequestMutation) AgentID() (r string, exists bool) {
	v := m.agent_id
	if v == nil {
		return
	}
	return *v, true
}

// OldAgentID returns the old "agent_id" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldAgentID(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAgentID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAgentID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAgentID: %w", err)
	}
	return oldValue.AgentID, nil
}

// ClearAgentID clears the value of the "agent_id" field.
func (m *RequestMutation) ClearAgentID() {
	m.agent_id = nil
	m.clearedFields[request.FieldAgentID] = struct{}{}
}

// AgentIDCleared returns if the "agent_id" field was cleared in this mutation.
func (m *RequestMutation) AgentIDCleared() bool {
	_, ok := m.clearedFields[request.FieldAgentID]
	return ok
}

// ResetAgentID resets all changes to the "agent_id" field.
func (m *RequestMutation) ResetAgentID() {
	m.agent_id = nil
	delete(m.clearedFields, request.FieldAgentID)
}

// SetMethod sets the "method" field.
func (m *RequestMutation) SetMethod(s string) {
	m.method = &s
}

// Method returns the value of the "method" field in the mutation.
func (m *RequestMutation) Method() (r string, exists bool) {
	v := m.method
	if v == nil {
		return
	}
	return *v, true
}

// OldMethod returns the old "method" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldMethod(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMethod is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMethod requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMethod: %w", err)
	}
	return oldValue.Method, nil
}

// ResetMethod resets all changes to the "method" field.
func (m *RequestMutation) ResetMethod() {
	m.method = nil
}

// SetPath sets the "path" field.
func (m *RequestMutation) SetPath(s string) {
	m._path = &s
}

// Path returns the value of the "path" field in the mutation.
func (m *RequestMutation) Path() (r string, exists bool) {
	v := m._path
	if v == nil {
		return
	}
	return *v, true
}

// OldPath returns the old "path" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldPath(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPath is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPath requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPath: %w", err)
	}
	return oldValue.Path, nil
}

// ResetPath resets all changes to the "path" field.
func (m *RequestMutation) ResetPath() {
	m._path = nil
}

// SetHeaders sets the "headers" field.
func (m *RequestMutation) SetHeaders(value map[string][]string) {
	m.headers = &value
}

// Headers returns the value of the "headers" field in the mutation.
func (m *RequestMutation) Headers() (r map[string][]string, exists bool) {
	v := m.headers
	if v == nil {
		return
	}
	return *v, true
}

// OldHeaders returns the old "headers" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldHeaders(ctx context.Context) (v map[string][]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeaders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeaders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeaders: %w", err)
	}
	return oldValue.Headers, nil
}

// ClearHeaders clears the value of the "headers" field.
func (m *RequestMutation) ClearHeaders() {
	m.headers = nil
	m.clearedFields[request.FieldHeaders] = struct{}{}
}

// HeadersCleared returns if the "headers" field was cleared in this mutation.
func (m *RequestMutation) HeadersCleared() bool {
	_, ok := m.clearedFields[request.FieldHeaders]
	return ok
}

// ResetHeaders resets all changes to the "headers" field.
func (m *RequestMutation) ResetHeaders() {
	m.headers = nil
	delete(m.clearedFields, request.FieldHeaders)
}

// SetBody sets the "body" field.
func (m *RequestMutation) SetBody(b []byte) {
	m.body = &b
}

// Body returns the value of the "body" field in the mutation.
func (m *RequestMutation) Body() (r []byte, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldBody(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ClearBody clears the value of the "body" field.
func (m *RequestMutation) ClearBody() {
	m.body = nil
	m.clearedFields[request.FieldBody] = struct{}{}
}

// BodyCleared returns if the "body" field was cleared in this mutation.
func (m *RequestMutation) BodyCleared() bool {
	_, ok := m.clearedFields[request.FieldBody]
	return ok
}

// ResetBody resets all changes to the "body" field.
func (m *RequestMutation) ResetBody() {
	m.body = nil
	delete(m.clearedFields, request.FieldBody)
}

// SetCreatedAt sets the "created_at" field.
func (m *RequestMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RequestMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Request entity.
// If the Request object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RequestMutation) ResetCreatedAt() {
	m.created_at = nil
}

// ClearGate clears the "gate" edge to the Gate entity.
func (m *RequestMutation) ClearGate() {
	m.clearedgate = true
	m.clearedFields[request.FieldGateID] = struct{}{}
}

// GateCleared reports if the "gate" edge to the Gate entity was cleared.
func (m *RequestMutation) GateCleared() bool {
	return m.clearedgate
}

// GateIDs returns the "gate" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// GateID instead. It exists only for internal usage by the builders.
func (m *RequestMutation) GateIDs() (ids []uuid.UUID) {
	if id := m.gate; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetGate resets all changes to the "gate" edge.
func (m *RequestMutation) ResetGate() {
	m.gate = nil
	m.clearedgate = false
}

// AddResponseIDs adds the "responses" edge to the Response entity by ids.
func (m *RequestMutation) AddResponseIDs(ids ...uuid.UUID) {
	if m.responses == nil {
		m.responses = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.responses[ids[i]] = struct{}{}
	}
}

// ClearResponses clears the "responses" edge to the Response entity.
func (m *RequestMutation) ClearResponses() {
	m.clearedresponses = true
}

// ResponsesCleared reports if the "responses" edge to the Response entity was cleared.
func (m *RequestMutation) ResponsesCleared() bool {
	return m.clearedresponses
}

// RemoveResponseIDs removes the "responses" edge to the Response entity by IDs.
func (m *RequestMutation) RemoveResponseIDs(ids ...uuid.UUID) {
	if m.removedresponses == nil {
		m.removedresponses = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.responses, ids[i])
		m.removedresponses[ids[i]] = struct{}{}
	}
}

// RemovedResponses returns the removed IDs of the "responses" edge to the Response entity.
func (m *RequestMutation) RemovedResponsesIDs() (ids []uuid.UUID) {
	for id := range m.removedresponses {
		ids = append(ids, id)
	}
	return
}

// ResponsesIDs returns the "responses" edge IDs in the mutation.
func (m *RequestMutation) ResponsesIDs() (ids []uuid.UUID) {
	for id := range m.responses {
		ids = append(ids, id)
	}
	return
}

// ResetResponses resets all changes to the "responses" edge.
func (m *RequestMutation) ResetResponses() {
	m.responses = nil
	m.clearedresponses = false
	m.removedresponses = nil
}

// SetDiffID sets the "diff" edge to the Diff entity by id.
func (m *RequestMutation) SetDiffID(id uuid.UUID) {
	m.diff = &id
}

// ClearDiff clears the "diff" edge to the Diff entity.
func (m *RequestMutation) ClearDiff() {
	m.cleareddiff = true
}

// DiffCleared reports if the "diff" edge to the Diff entity was cleared.
func (m *RequestMutation) DiffCleared() bool {
	return m.cleareddiff
}

// DiffID returns the "diff" edge ID in the mutation.
func (m *RequestMutation) DiffID() (id uuid.UUID, exists bool) {
	if m.diff != nil {
		return *m.diff, true
	}
	return
}

// DiffIDs returns the "diff" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// DiffID instead. It exists only for internal usage by the builders.
func (m *RequestMutation) DiffIDs() (ids []uuid.UUID) {
	if id := m.diff; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetDiff resets all changes to the "diff" edge.
func (m *RequestMutation) ResetDiff() {
	m.diff = nil
	m.cleareddiff = false
}

// Where appends a list predicates to the RequestMutation builder.
func (m *RequestMutation) Where(ps ...predicate.Request) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RequestMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RequestMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Request, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RequestMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RequestMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Request).
func (m *RequestMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RequestMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.gate != nil {
		fields = append(fields, request.FieldGateID)
	}
	if m.agent_id != nil {
		fields = append(fields, request.FieldAgentID)
	}
	if m.method != nil {
		fields = append(fields, request.FieldMethod)
	}
	if m._path != nil {
		fields = append(fields, request.FieldPath)
	}
	if m.headers != nil {
		fields = append(fields, request.FieldHeaders)
	}
	if m.body != nil {
		fields = append(fields, request.FieldBody)
	}
	if m.created_at != nil {
		fields = append(fields, request.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RequestMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case request.FieldGateID:
		return m.GateID()
	case request.FieldAgentID:
		return m.AgentID()
	case request.FieldMethod:
		return m.Method()
	case request.FieldPath:
		return m.Path()
	case request.FieldHeaders:
		return m.Headers()
	case request.FieldBody:
		return m.Body()
	case request.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RequestMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case request.FieldGateID:
		return m.OldGateID(ctx)
	case request.FieldAgentID:
		return m.OldAgentID(ctx)
	case request.FieldMethod:
		return m.OldMethod(ctx)
	case request.FieldPath:
		return m.OldPath(ctx)
	case request.FieldHeaders:
		return m.OldHeaders(ctx)
	case request.FieldBody:
		return m.OldBody(ctx)
	case request.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Request field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestMutation) SetField(name string, value ent.Value) error {
	switch name {
	case request.FieldGateID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGateID(v)
		return nil
	case request.FieldAgentID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAgentID(v)
		return nil
	case request.FieldMethod:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMethod(v)
		return nil
	case request.FieldPath:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPath(v)
		return nil
	case request.FieldHeaders:
		v, ok := value.(map[string][]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeaders(v)
		return nil
	case request.FieldBody:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case request.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Request field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RequestMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RequestMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Request numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RequestMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(request.FieldAgentID) {
		fields = append(fields, request.FieldAgentID)
	}
	if m.FieldCleared(request.FieldHeaders) {
		fields = append(fields, request.FieldHeaders)
	}
	if m.FieldCleared(request.FieldBody) {
		fields = append(fields, request.FieldBody)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RequestMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RequestMutation) ClearField(name string) error {
	switch name {
	case request.FieldAgentID:
		m.ClearAgentID()
		return nil
	case request.FieldHeaders:
		m.ClearHeaders()
		return nil
	case request.FieldBody:
		m.ClearBody()
		return nil
	}
	return fmt.Errorf("unknown Request nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RequestMutation) ResetField(name string) error {
	switch name {
	case request.FieldGateID:
		m.ResetGateID()
		return nil
	case request.FieldAgentID:
		m.ResetAgentID()
		return nil
	case request.FieldMethod:
		m.ResetMethod()
		return nil
	case request.FieldPath:
		m.ResetPath()
		return nil
	case request.FieldHeaders:
		m.ResetHeaders()
		return nil
	case request.FieldBody:
		m.ResetBody()
		return nil
	case request.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Request field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RequestMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.gate != nil {
		edges = append(edges, request.EdgeGate)
	}
	if m.responses != nil {
		edges = append(edges, request.EdgeResponses)
	}
	if m.diff != nil {
		edges = append(edges, request.EdgeDiff)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RequestMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case request.EdgeGate:
		if id := m.gate; id != nil {
			return []ent.Value{*id}
		}
	case request.EdgeResponses:
		ids := make([]ent.Value, 0, len(m.responses))
		for id := range m.responses {
			ids = append(ids, id)
		}
		return ids
	case request.EdgeDiff:
		if id := m.diff; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RequestMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedresponses != nil {
		edges = append(edges, request.EdgeResponses)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RequestMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case request.EdgeResponses:
		ids := make([]ent.Value, 0, len(m.removedresponses))
		for id := range m.removedresponses {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RequestMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedgate {
		edges = append(edges, request.EdgeGate)
	}
	if m.clearedresponses {
		edges = append(edges, request.EdgeResponses)
	}
	if m.cleareddiff {
		edges = append(edges, request.EdgeDiff)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RequestMutation) EdgeCleared(name string) bool {
	switch name {
	case request.EdgeGate:
		return m.clearedgate
	case request.EdgeResponses:
		return m.clearedresponses
	case request.EdgeDiff:
		return m.cleareddiff
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RequestMutation) ClearEdge(name string) error {
	switch name {
	case request.EdgeGate:
		m.ClearGate()
		return nil
	case request.EdgeDiff:
		m.ClearDiff()
		return nil
	}
	return fmt.Errorf("unknown Request unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RequestMutation) ResetEdge(name string) error {
	switch name {
	case request.EdgeGate:
		m.ResetGate()
		return nil
	case request.EdgeResponses:
		m.ResetResponses()
		return nil
	case request.EdgeDiff:
		m.ResetDiff()
		return nil
	}
	return fmt.Errorf("unknown Request edge %s", name)
}

// ResponseMutation represents an operation that mutates the Response nodes in the graph.
type ResponseMutation struct {
	config
	op                Op
	typ               string
	id                *uuid.UUID
	_type             *string
	status_code       *int32
	addstatus_code    *int32
	headers           *map[string][]string
	body              *[]byte
	created_at        *time.Time
	clearedFields     map[string]struct{}
	request           *uuid.UUID
	clearedrequest    bool
	diffs_from        map[uuid.UUID]struct{}
	removeddiffs_from map[uuid.UUID]struct{}
	cleareddiffs_from bool
	diffs_to          map[uuid.UUID]struct{}
	removeddiffs_to   map[uuid.UUID]struct{}
	cleareddiffs_to   bool
	done              bool
	oldValue          func(context.Context) (*Response, error)
	predicates        []predicate.Response
}

var _ ent.Mutation = (*ResponseMutation)(nil)

// responseOption allows management of the mutation configuration using functional options.
type responseOption func(*ResponseMutation)

// newResponseMutation creates new mutation for the Response entity.
func newResponseMutation(c config, op Op, opts ...responseOption) *ResponseMutation {
	m := &ResponseMutation{
		config:        c,
		op:            op,
		typ:           TypeResponse,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withResponseID sets the ID field of the mutation.
func withResponseID(id uuid.UUID) responseOption {
	return func(m *ResponseMutation) {
		var (
			err   error
			once  sync.Once
			value *Response
		)
		m.oldValue = func(ctx context.Context) (*Response, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Response.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withResponse sets the old Response of the mutation.
func withResponse(node *Response) responseOption {
	return func(m *ResponseMutation) {
		m.oldValue = func(context.Context) (*Response, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ResponseMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ResponseMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Response entities.
func (m *ResponseMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ResponseMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ResponseMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Response.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetRequestID sets the "request_id" field.
func (m *ResponseMutation) SetRequestID(u uuid.UUID) {
	m.request = &u
}

// RequestID returns the value of the "request_id" field in the mutation.
func (m *ResponseMutation) RequestID() (r uuid.UUID, exists bool) {
	v := m.request
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestID returns the old "request_id" field's value of the Response entity.
// If the Response object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ResponseMutation) OldRequestID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestID: %w", err)
	}
	return oldValue.RequestID, nil
}

// ResetRequestID resets all changes to the "request_id" field.
func (m *ResponseMutation) ResetRequestID() {
	m.request = nil
}

// SetType sets the "type" field.
func (m *ResponseMutation) SetType(s string) {
	m._type = &s
}

// GetType returns the value of the "type" field in the mutation.
func (m *ResponseMutation) GetType() (r string, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Response entity.
// If the Response object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ResponseMutation) OldType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *ResponseMutation) ResetType() {
	m._type = nil
}

// SetStatusCode sets the "status_code" field.
func (m *ResponseMutation) SetStatusCode(i int32) {
	m.status_code = &i
	m.addstatus_code = nil
}

// StatusCode returns the value of the "status_code" field in the mutation.
func (m *ResponseMutation) StatusCode() (r int32, exists bool) {
	v := m.status_code
	if v == nil {
		return
	}
	return *v, true
}

// OldStatusCode returns the old "status_code" field's value of the Response entity.
// If the Response object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ResponseMutation) OldStatusCode(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatusCode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatusCode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatusCode: %w", err)
	}
	return oldValue.StatusCode, nil
}

// AddStatusCode adds i to the "status_code" field.
func (m *ResponseMutation) AddStatusCode(i int32) {
	if m.addstatus_code != nil {
		*m.addstatus_code += i
	} else {
		m.addstatus_code = &i
	}
}

// AddedStatusCode returns the value that was added to the "status_code" field in this mutation.
func (m *ResponseMutation) AddedStatusCode() (r int32, exists bool) {
	v := m.addstatus_code
	if v == nil {
		return
	}
	return *v, true
}

// ResetStatusCode resets all changes to the "status_code" field.
func (m *ResponseMutation) ResetStatusCode() {
	m.status_code = nil
	m.addstatus_code = nil
}

// SetHeaders sets the "headers" field.
func (m *ResponseMutation) SetHeaders(value map[string][]string) {
	m.headers = &value
}

// Headers returns the value of the "headers" field in the mutation.
func (m *ResponseMutation) Headers() (r map[string][]string, exists bool) {
	v := m.headers
	if v == nil {
		return
	}
	return *v, true
}

// OldHeaders returns the old "headers" field's value of the Response entity.
// If the Response object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ResponseMutation) OldHeaders(ctx context.Context) (v map[string][]string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHeaders is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHeaders requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHeaders: %w", err)
	}
	return oldValue.Headers, nil
}

// ClearHeaders clears the value of the "headers" field.
func (m *ResponseMutation) ClearHeaders() {
	m.headers = nil
	m.clearedFields[response.FieldHeaders] = struct{}{}
}

// HeadersCleared returns if the "headers" field was cleared in this mutation.
func (m *ResponseMutation) HeadersCleared() bool {
	_, ok := m.clearedFields[response.FieldHeaders]
	return ok
}

// ResetHeaders resets all changes to the "headers" field.
func (m *ResponseMutation) ResetHeaders() {
	m.headers = nil
	delete(m.clearedFields, response.FieldHeaders)
}

// SetBody sets the "body" field.
func (m *ResponseMutation) SetBody(b []byte) {
	m.body = &b
}

// Body returns the value of the "body" field in the mutation.
func (m *ResponseMutation) Body() (r []byte, exists bool) {
	v := m.body
	if v == nil {
		return
	}
	return *v, true
}

// OldBody returns the old "body" field's value of the Response entity.
// If the Response object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ResponseMutation) OldBody(ctx context.Context) (v []byte, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBody is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBody requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBody: %w", err)
	}
	return oldValue.Body, nil
}

// ClearBody clears the value of the "body" field.
func (m *ResponseMutation) ClearBody() {
	m.body = nil
	m.clearedFields[response.FieldBody] = struct{}{}
}

// BodyCleared returns if the "body" field was cleared in this mutation.
func (m *ResponseMutation) BodyCleared() bool {
	_, ok := m.clearedFields[response.FieldBody]
	return ok
}

// ResetBody resets all changes to the "body" field.
func (m *ResponseMutation) ResetBody() {
	m.body = nil
	delete(m.clearedFields, response.FieldBody)
}

// SetCreatedAt sets the "created_at" field.
func (m *ResponseMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ResponseMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Response entity.
// If the Response object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ResponseMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ResponseMutation) ResetCreatedAt() {
	m.created_at = nil
}

// ClearRequest clears the "request" edge to the Request entity.
func (m *ResponseMutation) ClearRequest() {
	m.clearedrequest = true
	m.clearedFields[response.FieldRequestID] = struct{}{}
}

// RequestCleared reports if the "request" edge to the Request entity was cleared.
func (m *ResponseMutation) RequestCleared() bool {
	return m.clearedrequest
}

// RequestIDs returns the "request" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// RequestID instead. It exists only for internal usage by the builders.
func (m *ResponseMutation) RequestIDs() (ids []uuid.UUID) {
	if id := m.request; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetRequest resets all changes to the "request" edge.
func (m *ResponseMutation) ResetRequest() {
	m.request = nil
	m.clearedrequest = false
}

// AddDiffsFromIDs adds the "diffs_from" edge to the Diff entity by ids.
func (m *ResponseMutation) AddDiffsFromIDs(ids ...uuid.UUID) {
	if m.diffs_from == nil {
		m.diffs_from = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.diffs_from[ids[i]] = struct{}{}
	}
}

// ClearDiffsFrom clears the "diffs_from" edge to the Diff entity.
func (m *ResponseMutation) ClearDiffsFrom() {
	m.cleareddiffs_from = true
}

// DiffsFromCleared reports if the "diffs_from" edge to the Diff entity was cleared.
func (m *ResponseMutation) DiffsFromCleared() bool {
	return m.cleareddiffs_from
}

// RemoveDiffsFromIDs removes the "diffs_from" edge to the Diff entity by IDs.
func (m *ResponseMutation) RemoveDiffsFromIDs(ids ...uuid.UUID) {
	if m.removeddiffs_from == nil {
		m.removeddiffs_from = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.diffs_from, ids[i])
		m.removeddiffs_from[ids[i]] = struct{}{}
	}
}

// RemovedDiffsFrom returns the removed IDs of the "diffs_from" edge to the Diff entity.
func (m *ResponseMutation) RemovedDiffsFromIDs() (ids []uuid.UUID) {
	for id := range m.removeddiffs_from {
		ids = append(ids, id)
	}
	return
}

// DiffsFromIDs returns the "diffs_from" edge IDs in the mutation.
func (m *ResponseMutation) DiffsFromIDs() (ids []uuid.UUID) {
	for id := range m.diffs_from {
		ids = append(ids, id)
	}
	return
}

// ResetDiffsFrom resets all changes to the "diffs_from" edge.
func (m *ResponseMutation) ResetDiffsFrom() {
	m.diffs_from = nil
	m.cleareddiffs_from = false
	m.removeddiffs_from = nil
}

// AddDiffsToIDs adds the "diffs_to" edge to the Diff entity by ids.
func (m *ResponseMutation) AddDiffsToIDs(ids ...uuid.UUID) {
	if m.diffs_to == nil {
		m.diffs_to = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.diffs_to[ids[i]] = struct{}{}
	}
}

// ClearDiffsTo clears the "diffs_to" edge to the Diff entity.
func (m *ResponseMutation) ClearDiffsTo() {
	m.cleareddiffs_to = true
}

// DiffsToCleared reports if the "diffs_to" edge to the Diff entity was cleared.
func (m *ResponseMutation) DiffsToCleared() bool {
	return m.cleareddiffs_to
}

// RemoveDiffsToIDs removes the "diffs_to" edge to the Diff entity by IDs.
func (m *ResponseMutation) RemoveDiffsToIDs(ids ...uuid.UUID) {
	if m.removeddiffs_to == nil {
		m.removeddiffs_to = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.diffs_to, ids[i])
		m.removeddiffs_to[ids[i]] = struct{}{}
	}
}

// RemovedDiffsTo returns the removed IDs of the "diffs_to" edge to the Diff entity.
func (m *ResponseMutation) RemovedDiffsToIDs() (ids []uuid.UUID) {
	for id := range m.removeddiffs_to {
		ids = append(ids, id)
	}
	return
}

// DiffsToIDs returns the "diffs_to" edge IDs in the mutation.
func (m *ResponseMutation) DiffsToIDs() (ids []uuid.UUID) {
	for id := range m.diffs_to {
		ids = append(ids, id)
	}
	return
}

// ResetDiffsTo resets all changes to the "diffs_to" edge.
func (m *ResponseMutation) ResetDiffsTo() {
	m.diffs_to = nil
	m.cleareddiffs_to = false
	m.removeddiffs_to = nil
}

// Where appends a list predicates to the ResponseMutation builder.
func (m *ResponseMutation) Where(ps ...predicate.Response) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ResponseMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ResponseMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Response, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ResponseMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ResponseMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Response).
func (m *ResponseMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ResponseMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.request != nil {
		fields = append(fields, response.FieldRequestID)
	}
	if m._type != nil {
		fields = append(fields, response.FieldType)
	}
	if m.status_code != nil {
		fields = append(fields, response.FieldStatusCode)
	}
	if m.headers != nil {
		fields = append(fields, response.FieldHeaders)
	}
	if m.body != nil {
		fields = append(fields, response.FieldBody)
	}
	if m.created_at != nil {
		fields = append(fields, response.FieldCreatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ResponseMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case response.FieldRequestID:
		return m.RequestID()
	case response.FieldType:
		return m.GetType()
	case response.FieldStatusCode:
		return m.StatusCode()
	case response.FieldHeaders:
		return m.Headers()
	case response.FieldBody:
		return m.Body()
	case response.FieldCreatedAt:
		return m.CreatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ResponseMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case response.FieldRequestID:
		return m.OldRequestID(ctx)
	case response.FieldType:
		return m.OldType(ctx)
	case response.FieldStatusCode:
		return m.OldStatusCode(ctx)
	case response.FieldHeaders:
		return m.OldHeaders(ctx)
	case response.FieldBody:
		return m.OldBody(ctx)
	case response.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Response field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ResponseMutation) SetField(name string, value ent.Value) error {
	switch name {
	case response.FieldRequestID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestID(v)
		return nil
	case response.FieldType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case response.FieldStatusCode:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatusCode(v)
		return nil
	case response.FieldHeaders:
		v, ok := value.(map[string][]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHeaders(v)
		return nil
	case response.FieldBody:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBody(v)
		return nil
	case response.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Response field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ResponseMutation) AddedFields() []string {
	var fields []string
	if m.addstatus_code != nil {
		fields = append(fields, response.FieldStatusCode)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ResponseMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case response.FieldStatusCode:
		return m.AddedStatusCode()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ResponseMutation) AddField(name string, value ent.Value) error {
	switch name {
	case response.FieldStatusCode:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddStatusCode(v)
		return nil
	}
	return fmt.Errorf("unknown Response numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ResponseMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(response.FieldHeaders) {
		fields = append(fields, response.FieldHeaders)
	}
	if m.FieldCleared(response.FieldBody) {
		fields = append(fields, response.FieldBody)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ResponseMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ResponseMutation) ClearField(name string) error {
	switch name {
	case response.FieldHeaders:
		m.ClearHeaders()
		return nil
	case response.FieldBody:
		m.ClearBody()
		return nil
	}
	return fmt.Errorf("unknown Response nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ResponseMutation) ResetField(name string) error {
	switch name {
	case response.FieldRequestID:
		m.ResetRequestID()
		return nil
	case response.FieldType:
		m.ResetType()
		return nil
	case response.FieldStatusCode:
		m.ResetStatusCode()
		return nil
	case response.FieldHeaders:
		m.ResetHeaders()
		return nil
	case response.FieldBody:
		m.ResetBody()
		return nil
	case response.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	}
	return fmt.Errorf("unknown Response field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ResponseMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.request != nil {
		edges = append(edges, response.EdgeRequest)
	}
	if m.diffs_from != nil {
		edges = append(edges, response.EdgeDiffsFrom)
	}
	if m.diffs_to != nil {
		edges = append(edges, response.EdgeDiffsTo)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ResponseMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case response.EdgeRequest:
		if id := m.request; id != nil {
			return []ent.Value{*id}
		}
	case response.EdgeDiffsFrom:
		ids := make([]ent.Value, 0, len(m.diffs_from))
		for id := range m.diffs_from {
			ids = append(ids, id)
		}
		return ids
	case response.EdgeDiffsTo:
		ids := make([]ent.Value, 0, len(m.diffs_to))
		for id := range m.diffs_to {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ResponseMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removeddiffs_from != nil {
		edges = append(edges, response.EdgeDiffsFrom)
	}
	if m.removeddiffs_to != nil {
		edges = append(edges, response.EdgeDiffsTo)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ResponseMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case response.EdgeDiffsFrom:
		ids := make([]ent.Value, 0, len(m.removeddiffs_from))
		for id := range m.removeddiffs_from {
			ids = append(ids, id)
		}
		return ids
	case response.EdgeDiffsTo:
		ids := make([]ent.Value, 0, len(m.removeddiffs_to))
		for id := range m.removeddiffs_to {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ResponseMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedrequest {
		edges = append(edges, response.EdgeRequest)
	}
	if m.cleareddiffs_from {
		edges = append(edges, response.EdgeDiffsFrom)
	}
	if m.cleareddiffs_to {
		edges = append(edges, response.EdgeDiffsTo)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ResponseMutation) EdgeCleared(name string) bool {
	switch name {
	case response.EdgeRequest:
		return m.clearedrequest
	case response.EdgeDiffsFrom:
		return m.cleareddiffs_from
	case response.EdgeDiffsTo:
		return m.cleareddiffs_to
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ResponseMutation) ClearEdge(name string) error {
	switch name {
	case response.EdgeRequest:
		m.ClearRequest()
		return nil
	}
	return fmt.Errorf("unknown Response unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ResponseMutation) ResetEdge(name string) error {
	switch name {
	case response.EdgeRequest:
		m.ResetRequest()
		return nil
	case response.EdgeDiffsFrom:
		m.ResetDiffsFrom()
		return nil
	case response.EdgeDiffsTo:
		m.ResetDiffsTo()
		return nil
	}
	return fmt.Errorf("unknown Response edge %s", name)
}
