// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	entdiff "github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/gate"
	"github.com/pedrobarco/mroki/ent/request"
)

// Request is the model entity for the Request schema.
type Request struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// GateID holds the value of the "gate_id" field.
	GateID uuid.UUID `json:"gate_id,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Headers holds the value of the "headers" field.
	Headers map[string][]string `json:"headers,omitempty"`
	// Body holds the value of the "body" field.
	Body []byte `json:"body,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequestQuery when eager-loading is set.
	Edges        RequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequestEdges holds the relations/edges for other nodes in the graph.
type RequestEdges struct {
	// Gate holds the value of the gate edge.
	Gate *Gate `json:"gate,omitempty"`
	// Responses holds the value of the responses edge.
	Responses []*Response `json:"responses,omitempty"`
	// Diff holds the value of the diff edge.
	Diff *Diff `json:"diff,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// GateOrErr returns the Gate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestEdges) GateOrErr() (*Gate, error) {
	if e.Gate != nil {
		return e.Gate, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: gate.Label}
	}
	return nil, &NotLoadedError{edge: "gate"}
}

// ResponsesOrErr returns the Responses value or an error if the edge
// was not loaded in eager-loading.
func (e RequestEdges) ResponsesOrErr() ([]*Response, error) {
	if e.loadedTypes[1] {
		return e.Responses, nil
	}
	return nil, &NotLoadedError{edge: "responses"}
}

// DiffOrErr returns the Diff value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestEdges) DiffOrErr() (*Diff, error) {
	if e.Diff != nil {
		return e.Diff, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: entdiff.Label}
	}
	return nil, &NotLoadedError{edge: "diff"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Request) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case request.FieldHeaders, request.FieldBody:
			values[i] = new([]byte)
		case request.FieldMethod, request.FieldPath:
			values[i] = new(sql.NullString)
		case request.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case request.FieldID, request.FieldGateID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Request fields.
func (_m *Request) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case request.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case request.FieldGateID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field gate_id", values[i])
			} else if value != nil {
				_m.GateID = *value
			}
		case request.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case request.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case request.FieldHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Headers); err != nil {
					return fmt.Errorf("unmarshal field headers: %w", err)
				}
			}
		case request.FieldBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value != nil {
				_m.Body = *value
			}
		case request.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Request.
// This includes values selected through modifiers, order, etc.
func (_m *Request) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGate queries the "gate" edge of the Request entity.
func (_m *Request) QueryGate() *GateQuery {
	return NewRequestClient(_m.config).QueryGate(_m)
}

// QueryResponses queries the "responses" edge of the Request entity.
func (_m *Request) QueryResponses() *ResponseQuery {
	return NewRequestClient(_m.config).QueryResponses(_m)
}

// QueryDiff queries the "diff" edge of the Request entity.
func (_m *Request) QueryDiff() *DiffQuery {
	return NewRequestClient(_m.config).QueryDiff(_m)
}

// Update returns a builder for updating this Request.
// Note that you need to call Request.Unwrap() before calling this method if this Request
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Request) Update() *RequestUpdateOne {
	return NewRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Request entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Request) Unwrap() *Request {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Request is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Request) String() string {
	var builder strings.Builder
	builder.WriteString("Request(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("gate_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GateID))
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.Headers))
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(fmt.Sprintf("%v", _m.Body))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Requests is a parsable slice of Request.
type Requests []*Request
