// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/gate"
	"github.com/pedrobarco/mroki/ent/predicate"
	"github.com/pedrobarco/mroki/ent/request"
	"github.com/pedrobarco/mroki/ent/response"
)

// RequestUpdate is the builder for updating Request entities.
type RequestUpdate struct {
	config
	hooks    []Hook
	mutation *RequestMutation
}

// Where appends a list predicates to the RequestUpdate builder.
func (_u *RequestUpdate) Where(ps ...predicate.Request) *RequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGateID sets the "gate_id" field.
func (_u *RequestUpdate) SetGateID(v uuid.UUID) *RequestUpdate {
	_u.mutation.SetGateID(v)
	return _u
}

// SetNillableGateID sets the "gate_id" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableGateID(v *uuid.UUID) *RequestUpdate {
	if v != nil {
		_u.SetGateID(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *RequestUpdate) SetAgentID(v string) *RequestUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableAgentID(v *string) *RequestUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *RequestUpdate) ClearAgentID() *RequestUpdate {
	_u.mutation.ClearAgentID()
	return _u
}

// SetMethod sets the "method" field.
func (_u *RequestUpdate) SetMethod(v string) *RequestUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableMethod(v *string) *RequestUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *RequestUpdate) SetPath(v string) *RequestUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *RequestUpdate) SetNillablePath(v *string) *RequestUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *RequestUpdate) SetHeaders(v map[string][]string) *RequestUpdate {
	_u.mutation.SetHeaders(v)
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *RequestUpdate) ClearHeaders() *RequestUpdate {
	_u.mutation.ClearHeaders()
	return _u
}

// SetBody sets the "body" field.
func (_u *RequestUpdate) SetBody(v []byte) *RequestUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *RequestUpdate) ClearBody() *RequestUpdate {
	_u.mutation.ClearBody()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RequestUpdate) SetCreatedAt(v time.Time) *RequestUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableCreatedAt(v *time.Time) *RequestUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetGate sets the "gate" edge to the Gate entity.
func (_u *RequestUpdate) SetGate(v *Gate) *RequestUpdate {
	return _u.SetGateID(v.ID)
}

// AddResponseIDs adds the "responses" edge to the Response entity by IDs.
func (_u *RequestUpdate) AddResponseIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.AddResponseIDs(ids...)
	return _u
}

// AddResponses adds the "responses" edges to the Response entity.
func (_u *RequestUpdate) AddResponses(v ...*Response) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseIDs(ids...)
}

// SetDiffID sets the "diff" edge to the Diff entity by ID.
func (_u *RequestUpdate) SetDiffID(id uuid.UUID) *RequestUpdate {
	_u.mutation.SetDiffID(id)
	return _u
}

// SetNillableDiffID sets the "diff" edge to the Diff entity by ID if the given value is not nil.
func (_u *RequestUpdate) SetNillableDiffID(id *uuid.UUID) *RequestUpdate {
	if id != nil {
		_u = _u.SetDiffID(*id)
	}
	return _u
}

// SetDiff sets the "diff" edge to the Diff entity.
func (_u *RequestUpdate) SetDiff(v *Diff) *RequestUpdate {
	return _u.SetDiffID(v.ID)
}

// Mutation returns the RequestMutation object of the builder.
func (_u *RequestUpdate) Mutation() *RequestMutation {
	return _u.mutation
}

// ClearGate clears the "gate" edge to the Gate entity.
func (_u *RequestUpdate) ClearGate() *RequestUpdate {
	_u.mutation.ClearGate()
	return _u
}

// ClearResponses clears all "responses" edges to the Response entity.
func (_u *RequestUpdate) ClearResponses() *RequestUpdate {
	_u.mutation.ClearResponses()
	return _u
}

// RemoveResponseIDs removes the "responses" edge to Response entities by IDs.
func (_u *RequestUpdate) RemoveResponseIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.RemoveResponseIDs(ids...)
	return _u
}

// RemoveResponses removes "responses" edges to Response entities.
func (_u *RequestUpdate) RemoveResponses(v ...*Response) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseIDs(ids...)
}

// ClearDiff clears the "diff" edge to the Diff entity.
func (_u *RequestUpdate) ClearDiff() *RequestUpdate {
	_u.mutation.ClearDiff()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestUpdate) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := request.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Request.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := request.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Request.path": %w`, err)}
		}
	}
	if _u.mutation.GateCleared() && len(_u.mutation.GateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Request.gate"`)
	}
	return nil
}

func (_u *RequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(request.Table, request.Columns, sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(request.FieldAgentID, field.TypeString, value)
	}
	if _u.mutation.AgentIDCleared() {
		_spec.ClearField(request.FieldAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(request.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(request.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(request.FieldHeaders, field.TypeJSON, value)
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(request.FieldHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(request.FieldBody, field.TypeBytes, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(request.FieldBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(request.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.GateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.GateTable,
			Columns: []string{request.GateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.GateTable,
			Columns: []string{request.GateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.ResponsesTable,
			Columns: []string{request.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponsesIDs(); len(nodes) > 0 && !_u.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.ResponsesTable,
			Columns: []string{request.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.ResponsesTable,
			Columns: []string{request.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DiffCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   request.DiffTable,
			Columns: []string{request.DiffColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diff.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiffIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   request.DiffTable,
			Columns: []string{request.DiffColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diff.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{request.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestUpdateOne is the builder for updating a single Request entity.
type RequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestMutation
}

// SetGateID sets the "gate_id" field.
func (_u *RequestUpdateOne) SetGateID(v uuid.UUID) *RequestUpdateOne {
	_u.mutation.SetGateID(v)
	return _u
}

// SetNillableGateID sets the "gate_id" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableGateID(v *uuid.UUID) *RequestUpdateOne {
	if v != nil {
		_u.SetGateID(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *RequestUpdateOne) SetAgentID(v string) *RequestUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableAgentID(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *RequestUpdateOne) ClearAgentID() *RequestUpdateOne {
	_u.mutation.ClearAgentID()
	return _u
}

// SetMethod sets the "method" field.
func (_u *RequestUpdateOne) SetMethod(v string) *RequestUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableMethod(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *RequestUpdateOne) SetPath(v string) *RequestUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillablePath(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetHeaders sets the "headers" field.
func (_u *RequestUpdateOne) SetHeaders(v map[string][]string) *RequestUpdateOne {
	_u.mutation.SetHeaders(v)
	return _u
}

// ClearHeaders clears the value of the "headers" field.
func (_u *RequestUpdateOne) ClearHeaders() *RequestUpdateOne {
	_u.mutation.ClearHeaders()
	return _u
}

// SetBody sets the "body" field.
func (_u *RequestUpdateOne) SetBody(v []byte) *RequestUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// ClearBody clears the value of the "body" field.
func (_u *RequestUpdateOne) ClearBody() *RequestUpdateOne {
	_u.mutation.ClearBody()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RequestUpdateOne) SetCreatedAt(v time.Time) *RequestUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableCreatedAt(v *time.Time) *RequestUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetGate sets the "gate" edge to the Gate entity.
func (_u *RequestUpdateOne) SetGate(v *Gate) *RequestUpdateOne {
	return _u.SetGateID(v.ID)
}

// AddResponseIDs adds the "responses" edge to the Response entity by IDs.
func (_u *RequestUpdateOne) AddResponseIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.AddResponseIDs(ids...)
	return _u
}

// AddResponses adds the "responses" edges to the Response entity.
func (_u *RequestUpdateOne) AddResponses(v ...*Response) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseIDs(ids...)
}

// SetDiffID sets the "diff" edge to the Diff entity by ID.
func (_u *RequestUpdateOne) SetDiffID(id uuid.UUID) *RequestUpdateOne {
	_u.mutation.SetDiffID(id)
	return _u
}

// SetNillableDiffID sets the "diff" edge to the Diff entity by ID if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableDiffID(id *uuid.UUID) *RequestUpdateOne {
	if id != nil {
		_u = _u.SetDiffID(*id)
	}
	return _u
}

// SetDiff sets the "diff" edge to the Diff entity.
func (_u *RequestUpdateOne) SetDiff(v *Diff) *RequestUpdateOne {
	return _u.SetDiffID(v.ID)
}

// Mutation returns the RequestMutation object of the builder.
func (_u *RequestUpdateOne) Mutation() *RequestMutation {
	return _u.mutation
}

// ClearGate clears the "gate" edge to the Gate entity.
func (_u *RequestUpdateOne) ClearGate() *RequestUpdateOne {
	_u.mutation.ClearGate()
	return _u
}

// ClearResponses clears all "responses" edges to the Response entity.
func (_u *RequestUpdateOne) ClearResponses() *RequestUpdateOne {
	_u.mutation.ClearResponses()
	return _u
}

// RemoveResponseIDs removes the "responses" edge to Response entities by IDs.
func (_u *RequestUpdateOne) RemoveResponseIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.RemoveResponseIDs(ids...)
	return _u
}

// RemoveResponses removes "responses" edges to Response entities.
func (_u *RequestUpdateOne) RemoveResponses(v ...*Response) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseIDs(ids...)
}

// ClearDiff clears the "diff" edge to the Diff entity.
func (_u *RequestUpdateOne) ClearDiff() *RequestUpdateOne {
	_u.mutation.ClearDiff()
	return _u
}

// Where appends a list predicates to the RequestUpdate builder.
func (_u *RequestUpdateOne) Where(ps ...predicate.Request) *RequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestUpdateOne) Select(field string, fields ...string) *RequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Request entity.
func (_u *RequestUpdateOne) Save(ctx context.Context) (*Request, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestUpdateOne) SaveX(ctx context.Context) *Request {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestUpdateOne) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := request.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Request.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := request.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Request.path": %w`, err)}
		}
	}
	if _u.mutation.GateCleared() && len(_u.mutation.GateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Request.gate"`)
	}
	return nil
}

func (_u *RequestUpdateOne) sqlSave(ctx context.Context) (_node *Request, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(request.Table, request.Columns, sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Request.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, request.FieldID)
		for _, f := range fields {
			if !request.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != request.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(request.FieldAgentID, field.TypeString, value)
	}
	if _u.mutation.AgentIDCleared() {
		_spec.ClearField(request.FieldAgentID, field.TypeString)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(request.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(request.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Headers(); ok {
		_spec.SetField(request.FieldHeaders, field.TypeJSON, value)
	}
	if _u.mutation.HeadersCleared() {
		_spec.ClearField(request.FieldHeaders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(request.FieldBody, field.TypeBytes, value)
	}
	if _u.mutation.BodyCleared() {
		_spec.ClearField(request.FieldBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(request.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.GateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.GateTable,
			Columns: []string{request.GateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.GateTable,
			Columns: []string{request.GateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.ResponsesTable,
			Columns: []string{request.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponsesIDs(); len(nodes) > 0 && !_u.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.ResponsesTable,
			Columns: []string{request.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.ResponsesTable,
			Columns: []string{request.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DiffCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   request.DiffTable,
			Columns: []string{request.DiffColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diff.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiffIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   request.DiffTable,
			Columns: []string{request.DiffColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diff.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Request{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{request.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
