// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	entdiff "github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/gate"
	"github.com/pedrobarco/mroki/ent/request"
	"github.com/pedrobarco/mroki/ent/response"
)

// RequestCreate is the builder for creating a Request entity.
type RequestCreate struct {
	config
	mutation *RequestMutation
	hooks    []Hook
}

// SetGateID sets the "gate_id" field.
func (_c *RequestCreate) SetGateID(v uuid.UUID) *RequestCreate {
	_c.mutation.SetGateID(v)
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *RequestCreate) SetAgentID(v string) *RequestCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_c *RequestCreate) SetNillableAgentID(v *string) *RequestCreate {
	if v != nil {
		_c.SetAgentID(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *RequestCreate) SetMethod(v string) *RequestCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *RequestCreate) SetPath(v string) *RequestCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *RequestCreate) SetHeaders(v map[string][]string) *RequestCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *RequestCreate) SetBody(v []byte) *RequestCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestCreate) SetCreatedAt(v time.Time) *RequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RequestCreate) SetID(v uuid.UUID) *RequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RequestCreate) SetNillableID(v *uuid.UUID) *RequestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGate sets the "gate" edge to the Gate entity.
func (_c *RequestCreate) SetGate(v *Gate) *RequestCreate {
	return _c.SetGateID(v.ID)
}

// AddResponseIDs adds the "responses" edge to the Response entity by IDs.
func (_c *RequestCreate) AddResponseIDs(ids ...uuid.UUID) *RequestCreate {
	_c.mutation.AddResponseIDs(ids...)
	return _c
}

// AddResponses adds the "responses" edges to the Response entity.
func (_c *RequestCreate) AddResponses(v ...*Response) *RequestCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddResponseIDs(ids...)
}

// SetDiffID sets the "diff" edge to the Diff entity by ID.
func (_c *RequestCreate) SetDiffID(id uuid.UUID) *RequestCreate {
	_c.mutation.SetDiffID(id)
	return _c
}

// SetNillableDiffID sets the "diff" edge to the Diff entity by ID if the given value is not nil.
func (_c *RequestCreate) SetNillableDiffID(id *uuid.UUID) *RequestCreate {
	if id != nil {
		_c = _c.SetDiffID(*id)
	}
	return _c
}

// SetDiff sets the "diff" edge to the Diff entity.
func (_c *RequestCreate) SetDiff(v *Diff) *RequestCreate {
	return _c.SetDiffID(v.ID)
}

// Mutation returns the RequestMutation object of the builder.
func (_c *RequestCreate) Mutation() *RequestMutation {
	return _c.mutation
}

// Save creates the Request in the database.
func (_c *RequestCreate) Save(ctx context.Context) (*Request, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestCreate) SaveX(ctx context.Context) *Request {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := request.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestCreate) check() error {
	if _, ok := _c.mutation.GateID(); !ok {
		return &ValidationError{Name: "gate_id", err: errors.New(`ent: missing required field "Request.gate_id"`)}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "Request.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := request.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Request.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Request.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := request.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Request.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Request.created_at"`)}
	}
	if len(_c.mutation.GateIDs()) == 0 {
		return &ValidationError{Name: "gate", err: errors.New(`ent: missing required edge "Request.gate"`)}
	}
	return nil
}

func (_c *RequestCreate) sqlSave(ctx context.Context) (*Request, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestCreate) createSpec() (*Request, *sqlgraph.CreateSpec) {
	var (
		_node = &Request{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(request.Table, sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(request.FieldAgentID, field.TypeString, value)
		_node.AgentID = &value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(request.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(request.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(request.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(request.FieldBody, field.TypeBytes, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(request.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.GateTable,
			Columns: []string{request.GateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(gate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ResponsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.ResponsesTable,
			Columns: []string{request.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DiffIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   request.DiffTable,
			Columns: []string{request.DiffColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entdiff.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RequestCreateBulk is the builder for creating many Request entities in bulk.
type RequestCreateBulk struct {
	config
	err      error
	builders []*RequestCreate
}

// Save creates the Request entities in the database.
func (_c *RequestCreateBulk) Save(ctx context.Context) ([]*Request, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Request, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestCreateBulk) SaveX(ctx context.Context) []*Request {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
