// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	entdiff "github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/predicate"
	"github.com/pedrobarco/mroki/ent/request"
	"github.com/pedrobarco/mroki/ent/response"
)

// ResponseQuery is the builder for querying Response entities.
type ResponseQuery struct {
	config
	ctx           *QueryContext
	order         []response.OrderOption
	inters        []Interceptor
	predicates    []predicate.Response
	withRequest   *RequestQuery
	withDiffsFrom *DiffQuery
	withDiffsTo   *DiffQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResponseQuery builder.
func (_q *ResponseQuery) Where(ps ...predicate.Response) *ResponseQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ResponseQuery) Limit(limit int) *ResponseQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ResponseQuery) Offset(offset int) *ResponseQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ResponseQuery) Unique(unique bool) *ResponseQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ResponseQuery) Order(o ...response.OrderOption) *ResponseQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRequest chains the current query on the "request" edge.
func (_q *ResponseQuery) QueryRequest() *RequestQuery {
	query := (&RequestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(response.Table, response.FieldID, selector),
			sqlgraph.To(request.Table, request.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, response.RequestTable, response.RequestColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDiffsFrom chains the current query on the "diffs_from" edge.
func (_q *ResponseQuery) QueryDiffsFrom() *DiffQuery {
	query := (&DiffClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(response.Table, response.FieldID, selector),
			sqlgraph.To(entdiff.Table, entdiff.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, response.DiffsFromTable, response.DiffsFromColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDiffsTo chains the current query on the "diffs_to" edge.
func (_q *ResponseQuery) QueryDiffsTo() *DiffQuery {
	query := (&DiffClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(response.Table, response.FieldID, selector),
			sqlgraph.To(entdiff.Table, entdiff.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, response.DiffsToTable, response.DiffsToColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Response entity from the query.
// Returns a *NotFoundError when no Response was found.
func (_q *ResponseQuery) First(ctx context.Context) (*Response, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{response.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ResponseQuery) FirstX(ctx context.Context) *Response {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Response ID from the query.
// Returns a *NotFoundError when no Response ID was found.
func (_q *ResponseQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{response.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ResponseQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Response entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Response entity is found.
// Returns a *NotFoundError when no Response entities are found.
func (_q *ResponseQuery) Only(ctx context.Context) (*Response, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{response.Label}
	default:
		return nil, &NotSingularError{response.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ResponseQuery) OnlyX(ctx context.Context) *Response {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Response ID in the query.
// Returns a *NotSingularError when more than one Response ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ResponseQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{response.Label}
	default:
		err = &NotSingularError{response.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ResponseQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Responses.
func (_q *ResponseQuery) All(ctx context.Context) ([]*Response, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Response, *ResponseQuery]()
	return withInterceptors[[]*Response](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ResponseQuery) AllX(ctx context.Context) []*Response {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Response IDs.
func (_q *ResponseQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(response.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ResponseQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ResponseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ResponseQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ResponseQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ResponseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ResponseQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResponseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ResponseQuery) Clone() *ResponseQuery {
	if _q == nil {
		return nil
	}
	return &ResponseQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]response.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Response{}, _q.predicates...),
		withRequest:   _q.withRequest.Clone(),
		withDiffsFrom: _q.withDiffsFrom.Clone(),
		withDiffsTo:   _q.withDiffsTo.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRequest tells the query-builder to eager-load the nodes that are connected to
// the "request" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResponseQuery) WithRequest(opts ...func(*RequestQuery)) *ResponseQuery {
	query := (&RequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRequest = query
	return _q
}

// WithDiffsFrom tells the query-builder to eager-load the nodes that are connected to
// the "diffs_from" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResponseQuery) WithDiffsFrom(opts ...func(*DiffQuery)) *ResponseQuery {
	query := (&DiffClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDiffsFrom = query
	return _q
}

// WithDiffsTo tells the query-builder to eager-load the nodes that are connected to
// the "diffs_to" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResponseQuery) WithDiffsTo(opts ...func(*DiffQuery)) *ResponseQuery {
	query := (&DiffClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDiffsTo = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequestID uuid.UUID `json:"request_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Response.Query().
//		GroupBy(response.FieldRequestID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ResponseQuery) GroupBy(field string, fields ...string) *ResponseGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ResponseGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = response.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequestID uuid.UUID `json:"request_id,omitempty"`
//	}
//
//	client.Response.Query().
//		Select(response.FieldRequestID).
//		Scan(ctx, &v)
func (_q *ResponseQuery) Select(fields ...string) *ResponseSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ResponseSelect{ResponseQuery: _q}
	sbuild.label = response.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ResponseSelect configured with the given aggregations.
func (_q *ResponseQuery) Aggregate(fns ...AggregateFunc) *ResponseSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ResponseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !response.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ResponseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Response, error) {
	var (
		nodes       = []*Response{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withRequest != nil,
			_q.withDiffsFrom != nil,
			_q.withDiffsTo != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Response).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Response{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRequest; query != nil {
		if err := _q.loadRequest(ctx, query, nodes, nil,
			func(n *Response, e *Request) { n.Edges.Request = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDiffsFrom; query != nil {
		if err := _q.loadDiffsFrom(ctx, query, nodes,
			func(n *Response) { n.Edges.DiffsFrom = []*Diff{} },
			func(n *Response, e *Diff) { n.Edges.DiffsFrom = append(n.Edges.DiffsFrom, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDiffsTo; query != nil {
		if err := _q.loadDiffsTo(ctx, query, nodes,
			func(n *Response) { n.Edges.DiffsTo = []*Diff{} },
			func(n *Response, e *Diff) { n.Edges.DiffsTo = append(n.Edges.DiffsTo, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ResponseQuery) loadRequest(ctx context.Context, query *RequestQuery, nodes []*Response, init func(*Response), assign func(*Response, *Request)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Response)
	for i := range nodes {
		fk := nodes[i].RequestID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(request.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "request_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ResponseQuery) loadDiffsFrom(ctx context.Context, query *DiffQuery, nodes []*Response, init func(*Response), assign func(*Response, *Diff)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Response)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(entdiff.FieldFromResponseID)
	}
	query.Where(predicate.Diff(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(response.DiffsFromColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FromResponseID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "from_response_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ResponseQuery) loadDiffsTo(ctx context.Context, query *DiffQuery, nodes []*Response, init func(*Response), assign func(*Response, *Diff)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Response)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(entdiff.FieldToResponseID)
	}
	query.Where(predicate.Diff(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(response.DiffsToColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ToResponseID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "to_response_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ResponseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ResponseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(response.Table, response.Columns, sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, response.FieldID)
		for i := range fields {
			if fields[i] != response.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRequest != nil {
			_spec.Node.AddColumnOnce(response.FieldRequestID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ResponseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(response.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = response.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ResponseGroupBy is the group-by builder for Response entities.
type ResponseGroupBy struct {
	selector
	build *ResponseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ResponseGroupBy) Aggregate(fns ...AggregateFunc) *ResponseGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ResponseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResponseQuery, *ResponseGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ResponseGroupBy) sqlScan(ctx context.Context, root *ResponseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ResponseSelect is the builder for selecting fields of Response entities.
type ResponseSelect struct {
	*ResponseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ResponseSelect) Aggregate(fns ...AggregateFunc) *ResponseSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ResponseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResponseQuery, *ResponseSelect](ctx, _s.ResponseQuery, _s, _s.inters, v)
}

func (_s *ResponseSelect) sqlScan(ctx context.Context, root *ResponseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
