// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/request"
	"github.com/pedrobarco/mroki/ent/response"
)

// ResponseCreate is the builder for creating a Response entity.
type ResponseCreate struct {
	config
	mutation *ResponseMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (_c *ResponseCreate) SetRequestID(v uuid.UUID) *ResponseCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ResponseCreate) SetType(v string) *ResponseCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *ResponseCreate) SetStatusCode(v int32) *ResponseCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *ResponseCreate) SetHeaders(v map[string][]string) *ResponseCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *ResponseCreate) SetBody(v []byte) *ResponseCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResponseCreate) SetCreatedAt(v time.Time) *ResponseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ResponseCreate) SetID(v uuid.UUID) *ResponseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ResponseCreate) SetNillableID(v *uuid.UUID) *ResponseCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRequest sets the "request" edge to the Request entity.
func (_c *ResponseCreate) SetRequest(v *Request) *ResponseCreate {
	return _c.SetRequestID(v.ID)
}

// AddDiffsFromIDs adds the "diffs_from" edge to the Diff entity by IDs.
func (_c *ResponseCreate) AddDiffsFromIDs(ids ...uuid.UUID) *ResponseCreate {
	_c.mutation.AddDiffsFromIDs(ids...)
	return _c
}

// AddDiffsFrom adds the "diffs_from" edges to the Diff entity.
func (_c *ResponseCreate) AddDiffsFrom(v ...*Diff) *ResponseCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDiffsFromIDs(ids...)
}

// AddDiffsToIDs adds the "diffs_to" edge to the Diff entity by IDs.
func (_c *ResponseCreate) AddDiffsToIDs(ids ...uuid.UUID) *ResponseCreate {
	_c.mutation.AddDiffsToIDs(ids...)
	return _c
}

// AddDiffsTo adds the "diffs_to" edges to the Diff entity.
func (_c *ResponseCreate) AddDiffsTo(v ...*Diff) *ResponseCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDiffsToIDs(ids...)
}

// Mutation returns the ResponseMutation object of the builder.
func (_c *ResponseCreate) Mutation() *ResponseMutation {
	return _c.mutation
}

// Save creates the Response in the database.
func (_c *ResponseCreate) Save(ctx context.Context) (*Response, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResponseCreate) SaveX(ctx context.Context) *Response {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResponseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResponseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResponseCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := response.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResponseCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "Response.request_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Response.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := response.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Response.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "Response.status_code"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Response.created_at"`)}
	}
	if len(_c.mutation.RequestIDs()) == 0 {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required edge "Response.request"`)}
	}
	return nil
}

func (_c *ResponseCreate) sqlSave(ctx context.Context) (*Response, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResponseCreate) createSpec() (*Response, *sqlgraph.CreateSpec) {
	var (
		_node = &Response{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(response.Table, sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(response.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(response.FieldStatusCode, field.TypeInt32, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(response.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(response.FieldBody, field.TypeBytes, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(response.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   response.RequestTable,
			Columns: []string{response.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DiffsFromIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   response.DiffsFromTable,
			Columns: []string{response.DiffsFromColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diff.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DiffsToIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   response.DiffsToTable,
			Columns: []string{response.DiffsToColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diff.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResponseCreateBulk is the builder for creating many Response entities in bulk.
type ResponseCreateBulk struct {
	config
	err      error
	builders []*ResponseCreate
}

// Save creates the Response entities in the database.
func (_c *ResponseCreateBulk) Save(ctx context.Context) ([]*Response, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Response, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResponseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResponseCreateBulk) SaveX(ctx context.Context) []*Response {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResponseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResponseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
