// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/request"
	"github.com/pedrobarco/mroki/ent/response"
)

// Response is the model entity for the Response schema.
type Response struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID uuid.UUID `json:"request_id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode int32 `json:"status_code,omitempty"`
	// Headers holds the value of the "headers" field.
	Headers map[string][]string `json:"headers,omitempty"`
	// Body holds the value of the "body" field.
	Body []byte `json:"body,omitempty"`
	// LatencyMs holds the value of the "latency_ms" field.
	LatencyMs int64 `json:"latency_ms,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResponseQuery when eager-loading is set.
	Edges        ResponseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResponseEdges holds the relations/edges for other nodes in the graph.
type ResponseEdges struct {
	// Request holds the value of the request edge.
	Request *Request `json:"request,omitempty"`
	// DiffsFrom holds the value of the diffs_from edge.
	DiffsFrom []*Diff `json:"diffs_from,omitempty"`
	// DiffsTo holds the value of the diffs_to edge.
	DiffsTo []*Diff `json:"diffs_to,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// RequestOrErr returns the Request value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResponseEdges) RequestOrErr() (*Request, error) {
	if e.Request != nil {
		return e.Request, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: request.Label}
	}
	return nil, &NotLoadedError{edge: "request"}
}

// DiffsFromOrErr returns the DiffsFrom value or an error if the edge
// was not loaded in eager-loading.
func (e ResponseEdges) DiffsFromOrErr() ([]*Diff, error) {
	if e.loadedTypes[1] {
		return e.DiffsFrom, nil
	}
	return nil, &NotLoadedError{edge: "diffs_from"}
}

// DiffsToOrErr returns the DiffsTo value or an error if the edge
// was not loaded in eager-loading.
func (e ResponseEdges) DiffsToOrErr() ([]*Diff, error) {
	if e.loadedTypes[2] {
		return e.DiffsTo, nil
	}
	return nil, &NotLoadedError{edge: "diffs_to"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Response) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case response.FieldHeaders, response.FieldBody:
			values[i] = new([]byte)
		case response.FieldStatusCode, response.FieldLatencyMs:
			values[i] = new(sql.NullInt64)
		case response.FieldType:
			values[i] = new(sql.NullString)
		case response.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case response.FieldID, response.FieldRequestID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Response fields.
func (_m *Response) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case response.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case response.FieldRequestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value != nil {
				_m.RequestID = *value
			}
		case response.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case response.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = int32(value.Int64)
			}
		case response.FieldHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Headers); err != nil {
					return fmt.Errorf("unmarshal field headers: %w", err)
				}
			}
		case response.FieldBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value != nil {
				_m.Body = *value
			}
		case response.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = value.Int64
			}
		case response.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Response.
// This includes values selected through modifiers, order, etc.
func (_m *Response) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequest queries the "request" edge of the Response entity.
func (_m *Response) QueryRequest() *RequestQuery {
	return NewResponseClient(_m.config).QueryRequest(_m)
}

// QueryDiffsFrom queries the "diffs_from" edge of the Response entity.
func (_m *Response) QueryDiffsFrom() *DiffQuery {
	return NewResponseClient(_m.config).QueryDiffsFrom(_m)
}

// QueryDiffsTo queries the "diffs_to" edge of the Response entity.
func (_m *Response) QueryDiffsTo() *DiffQuery {
	return NewResponseClient(_m.config).QueryDiffsTo(_m)
}

// Update returns a builder for updating this Response.
// Note that you need to call Response.Unwrap() before calling this method if this Response
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Response) Update() *ResponseUpdateOne {
	return NewResponseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Response entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Response) Unwrap() *Response {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Response is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Response) String() string {
	var builder strings.Builder
	builder.WriteString("Response(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.Headers))
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(fmt.Sprintf("%v", _m.Body))
	builder.WriteString(", ")
	builder.WriteString("latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatencyMs))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Responses is a parsable slice of Response.
type Responses []*Response
