// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/diff"
	"github.com/pedrobarco/mroki/ent/gate"
	"github.com/pedrobarco/mroki/ent/request"
	"github.com/pedrobarco/mroki/ent/response"
	"github.com/pedrobarco/mroki/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	diffFields := schema.Diff{}.Fields()
	_ = diffFields
	// diffDescCreatedAt is the schema descriptor for created_at field.
	diffDescCreatedAt := diffFields[5].Descriptor()
	// diff.DefaultCreatedAt holds the default value on creation for the created_at field.
	diff.DefaultCreatedAt = diffDescCreatedAt.Default.(func() time.Time)
	// diffDescID is the schema descriptor for id field.
	diffDescID := diffFields[0].Descriptor()
	// diff.DefaultID holds the default value on creation for the id field.
	diff.DefaultID = diffDescID.Default.(func() uuid.UUID)
	gateFields := schema.Gate{}.Fields()
	_ = gateFields
	// gateDescLiveURL is the schema descriptor for live_url field.
	gateDescLiveURL := gateFields[1].Descriptor()
	// gate.LiveURLValidator is a validator for the "live_url" field. It is called by the builders before save.
	gate.LiveURLValidator = gateDescLiveURL.Validators[0].(func(string) error)
	// gateDescShadowURL is the schema descriptor for shadow_url field.
	gateDescShadowURL := gateFields[2].Descriptor()
	// gate.ShadowURLValidator is a validator for the "shadow_url" field. It is called by the builders before save.
	gate.ShadowURLValidator = gateDescShadowURL.Validators[0].(func(string) error)
	// gateDescID is the schema descriptor for id field.
	gateDescID := gateFields[0].Descriptor()
	// gate.DefaultID holds the default value on creation for the id field.
	gate.DefaultID = gateDescID.Default.(func() uuid.UUID)
	requestFields := schema.Request{}.Fields()
	_ = requestFields
	// requestDescMethod is the schema descriptor for method field.
	requestDescMethod := requestFields[3].Descriptor()
	// request.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	request.MethodValidator = requestDescMethod.Validators[0].(func(string) error)
	// requestDescPath is the schema descriptor for path field.
	requestDescPath := requestFields[4].Descriptor()
	// request.PathValidator is a validator for the "path" field. It is called by the builders before save.
	request.PathValidator = requestDescPath.Validators[0].(func(string) error)
	// requestDescID is the schema descriptor for id field.
	requestDescID := requestFields[0].Descriptor()
	// request.DefaultID holds the default value on creation for the id field.
	request.DefaultID = requestDescID.Default.(func() uuid.UUID)
	responseFields := schema.Response{}.Fields()
	_ = responseFields
	// responseDescType is the schema descriptor for type field.
	responseDescType := responseFields[2].Descriptor()
	// response.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	response.TypeValidator = responseDescType.Validators[0].(func(string) error)
	// responseDescID is the schema descriptor for id field.
	responseDescID := responseFields[0].Descriptor()
	// response.DefaultID holds the default value on creation for the id field.
	response.DefaultID = responseDescID.Default.(func() uuid.UUID)
}
