// Code generated by ent, DO NOT EDIT.

package request

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/pedrobarco/mroki/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldLTE(FieldID, id))
}

// GateID applies equality check predicate on the "gate_id" field. It's identical to GateIDEQ.
func GateID(v uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldGateID, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldMethod, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldPath, v))
}

// RawQuery applies equality check predicate on the "raw_query" field. It's identical to RawQueryEQ.
func RawQuery(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldRawQuery, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldCreatedAt, v))
}

// GateIDEQ applies the EQ predicate on the "gate_id" field.
func GateIDEQ(v uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldGateID, v))
}

// GateIDNEQ applies the NEQ predicate on the "gate_id" field.
func GateIDNEQ(v uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldGateID, v))
}

// GateIDIn applies the In predicate on the "gate_id" field.
func GateIDIn(vs ...uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldGateID, vs...))
}

// GateIDNotIn applies the NotIn predicate on the "gate_id" field.
func GateIDNotIn(vs ...uuid.UUID) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldGateID, vs...))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.Request {
	return predicate.Request(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.Request {
	return predicate.Request(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.Request {
	return predicate.Request(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.Request {
	return predicate.Request(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.Request {
	return predicate.Request(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.Request {
	return predicate.Request(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.Request {
	return predicate.Request(sql.FieldContainsFold(FieldMethod, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.Request {
	return predicate.Request(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.Request {
	return predicate.Request(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.Request {
	return predicate.Request(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.Request {
	return predicate.Request(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.Request {
	return predicate.Request(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.Request {
	return predicate.Request(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.Request {
	return predicate.Request(sql.FieldContainsFold(FieldPath, v))
}

// RawQueryEQ applies the EQ predicate on the "raw_query" field.
func RawQueryEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldRawQuery, v))
}

// RawQueryNEQ applies the NEQ predicate on the "raw_query" field.
func RawQueryNEQ(v string) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldRawQuery, v))
}

// RawQueryIn applies the In predicate on the "raw_query" field.
func RawQueryIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldRawQuery, vs...))
}

// RawQueryNotIn applies the NotIn predicate on the "raw_query" field.
func RawQueryNotIn(vs ...string) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldRawQuery, vs...))
}

// RawQueryGT applies the GT predicate on the "raw_query" field.
func RawQueryGT(v string) predicate.Request {
	return predicate.Request(sql.FieldGT(FieldRawQuery, v))
}

// RawQueryGTE applies the GTE predicate on the "raw_query" field.
func RawQueryGTE(v string) predicate.Request {
	return predicate.Request(sql.FieldGTE(FieldRawQuery, v))
}

// RawQueryLT applies the LT predicate on the "raw_query" field.
func RawQueryLT(v string) predicate.Request {
	return predicate.Request(sql.FieldLT(FieldRawQuery, v))
}

// RawQueryLTE applies the LTE predicate on the "raw_query" field.
func RawQueryLTE(v string) predicate.Request {
	return predicate.Request(sql.FieldLTE(FieldRawQuery, v))
}

// RawQueryContains applies the Contains predicate on the "raw_query" field.
func RawQueryContains(v string) predicate.Request {
	return predicate.Request(sql.FieldContains(FieldRawQuery, v))
}

// RawQueryHasPrefix applies the HasPrefix predicate on the "raw_query" field.
func RawQueryHasPrefix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasPrefix(FieldRawQuery, v))
}

// RawQueryHasSuffix applies the HasSuffix predicate on the "raw_query" field.
func RawQueryHasSuffix(v string) predicate.Request {
	return predicate.Request(sql.FieldHasSuffix(FieldRawQuery, v))
}

// RawQueryIsNil applies the IsNil predicate on the "raw_query" field.
func RawQueryIsNil() predicate.Request {
	return predicate.Request(sql.FieldIsNull(FieldRawQuery))
}

// RawQueryNotNil applies the NotNil predicate on the "raw_query" field.
func RawQueryNotNil() predicate.Request {
	return predicate.Request(sql.FieldNotNull(FieldRawQuery))
}

// RawQueryEqualFold applies the EqualFold predicate on the "raw_query" field.
func RawQueryEqualFold(v string) predicate.Request {
	return predicate.Request(sql.FieldEqualFold(FieldRawQuery, v))
}

// RawQueryContainsFold applies the ContainsFold predicate on the "raw_query" field.
func RawQueryContainsFold(v string) predicate.Request {
	return predicate.Request(sql.FieldContainsFold(FieldRawQuery, v))
}

// HeadersIsNil applies the IsNil predicate on the "headers" field.
func HeadersIsNil() predicate.Request {
	return predicate.Request(sql.FieldIsNull(FieldHeaders))
}

// HeadersNotNil applies the NotNil predicate on the "headers" field.
func HeadersNotNil() predicate.Request {
	return predicate.Request(sql.FieldNotNull(FieldHeaders))
}

// BodyIsNil applies the IsNil predicate on the "body" field.
func BodyIsNil() predicate.Request {
	return predicate.Request(sql.FieldIsNull(FieldBody))
}

// BodyNotNil applies the NotNil predicate on the "body" field.
func BodyNotNil() predicate.Request {
	return predicate.Request(sql.FieldNotNull(FieldBody))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Request {
	return predicate.Request(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Request {
	return predicate.Request(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Request {
	return predicate.Request(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Request {
	return predicate.Request(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Request {
	return predicate.Request(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Request {
	return predicate.Request(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Request {
	return predicate.Request(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Request {
	return predicate.Request(sql.FieldLTE(FieldCreatedAt, v))
}

// HasGate applies the HasEdge predicate on the "gate" edge.
func HasGate() predicate.Request {
	return predicate.Request(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GateTable, GateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGateWith applies the HasEdge predicate on the "gate" edge with a given conditions (other predicates).
func HasGateWith(preds ...predicate.Gate) predicate.Request {
	return predicate.Request(func(s *sql.Selector) {
		step := newGateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResponses applies the HasEdge predicate on the "responses" edge.
func HasResponses() predicate.Request {
	return predicate.Request(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ResponsesTable, ResponsesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResponsesWith applies the HasEdge predicate on the "responses" edge with a given conditions (other predicates).
func HasResponsesWith(preds ...predicate.Response) predicate.Request {
	return predicate.Request(func(s *sql.Selector) {
		step := newResponsesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDiff applies the HasEdge predicate on the "diff" edge.
func HasDiff() predicate.Request {
	return predicate.Request(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, DiffTable, DiffColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDiffWith applies the HasEdge predicate on the "diff" edge with a given conditions (other predicates).
func HasDiffWith(preds ...predicate.Diff) predicate.Request {
	return predicate.Request(func(s *sql.Selector) {
		step := newDiffStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Request) predicate.Request {
	return predicate.Request(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Request) predicate.Request {
	return predicate.Request(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Request) predicate.Request {
	return predicate.Request(sql.NotPredicates(p))
}
