name: lint-build-test-go

on:
  workflow_call:
    inputs:
      targets:
        description: 'JSON array of Go packages to build'
        required: true
        type: string

jobs:
  lint-build-test:
    name: lint-build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-go

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4

      - name: Test
        run: gotestsum --format github-actions ./...

      - name: Build
        run: |
          targets=$(echo '${{ inputs.targets }}' | jq -r '.[] | "./\(.)/..."')
          CGO_ENABLED=0 go build $targets
