services:
  mroki-db:
    extends:
      file: ../../build/package/mroki-db/compose.yaml
      service: mroki-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mroki

  mroki-api:
    extends:
      file: ../../build/package/mroki-api/compose.yaml
      service: mroki-api
    image: mroki-api:latest
    environment:
      MROKI_APP_PORT: 8081
      MROKI_APP_DATABASE_URL: postgres://postgres:${DB_PASSWORD}@mroki-db:5432/mroki
    ports:
      - "8081:8081"
    depends_on:
      mroki-db:
        condition: service_healthy

  mroki-proxy:
    extends:
      file: ../../build/package/mroki-proxy/compose.yaml
      service: mroki-proxy
    image: mroki-proxy:latest
    environment:
      MROKI_APP_LIVE_URL: ${LIVE_URL}
      MROKI_APP_SHADOW_URL: ${SHADOW_URL}
      MROKI_APP_PORT: 8080
      MROKI_APP_API_URL: http://mroki-api:8081
      MROKI_APP_GATE_ID: ${GATE_ID}
    depends_on:
      - mroki-api

  mroki-hub:
    extends:
      file: ../../build/package/mroki-hub/compose.yaml
      service: mroki-hub
    image: mroki-hub:latest
    environment:
      MROKI_API_BASE_URL: ${MROKI_API_BASE_URL:-}
      MROKI_API_KEY: ${MROKI_APP_API_KEY:-}
    depends_on:
      - mroki-api

volumes:
  mroki-db-data:
