// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Diff is the predicate function for entdiff builders.
type Diff func(*sql.Selector)

// Gate is the predicate function for gate builders.
type Gate func(*sql.Selector)

// Request is the predicate function for request builders.
type Request func(*sql.Selector)

// Response is the predicate function for response builders.
type Response func(*sql.Selector)
